import type { Location } from "@/types";

// ────────────────────────────────────────────────────────────
//  Mock locations — all real Astana recycling points
//  sourced from v1 (green-map-astana) + expanded
// ────────────────────────────────────────────────────────────

export const mockLocations: Location[] = [
  // ── BIG HUBS (category: "hub") ──────────────────────────────

  {
    id: "1",
    slug: "kazrecycle-service",
    category: "hub",
    name: {
      ru: "KazRecycleService ТОО",
      en: "KazRecycleService LLP",
      kk: "KazRecycleService ЖШС",
    },
    description: {
      ru: "Крупный промышленный переработчик. Принимает пластик, бумагу, стекло и металл оптом от организаций и частных лиц.",
      en: "Major industrial recycler. Accepts plastic, paper, glass and metal in bulk from organisations and individuals.",
      kk: "Ірі өнеркәсіптік қайта өңдеуші. Ұйымдардан және жеке тұлғалардан жаппай пластик, қағаз, шыны және металл қабылдайды.",
    },
    address: {
      ru: "Промышленная зона, ул. Металлургов 12",
      en: "Industrial zone, Metallurgov St 12",
      kk: "Өнеркәсіп аймағы, Металлургтар к. 12",
    },
    position: { lat: 51.1522, lng: 71.4891 },
    materials: ["plastic", "paper", "glass", "metal", "industrial"],
    schedule: { weekdays: "08:00–18:00", saturday: "09:00–14:00", sunday: null },
    phone: "+7 (7172) 45-12-33",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    slug: "ls-ecolife-hub",
    category: "hub",
    name: {
      ru: "LS Ecolife — Центральный хаб",
      en: "LS Ecolife — Central Hub",
      kk: "LS Ecolife — Орталық хаб",
    },
    description: {
      ru: "Главный центр сбора вторсырья сети LS Ecolife. Принимает широкий спектр материалов, есть консультант.",
      en: "Main collection centre of the LS Ecolife network. Wide range of materials accepted, staff on site.",
      kk: "LS Ecolife желісінің негізгі жинау орталығы. Материалдардың кең ауқымы қабылданады, кеңесші бар.",
    },
    address: {
      ru: "ул. Сарыарқа 31А",
      en: "Saryarka St 31A",
      kk: "Сарыарқа к. 31А",
    },
    position: { lat: 51.1405, lng: 71.4018 },
    materials: ["plastic", "paper", "glass", "metal", "aluminium", "bottles"],
    schedule: { weekdays: "09:00–19:00", saturday: "10:00–17:00", sunday: null },
    phone: "+7 (7172) 30-77-88",
    website: "https://lsecolife.kz",
    photos: [],
    verified: true,
    createdAt: "2024-01-15",
  },
  {
    id: "3",
    slug: "astana-taza-alem",
    category: "hub",
    name: {
      ru: "Astana Taza Alem",
      en: "Astana Taza Alem",
      kk: "Astana Taza Älem",
    },
    description: {
      ru: "Экологический центр с образовательными программами. Принимает вторсырьё от жителей города.",
      en: "Ecological centre with educational programmes. Collects recyclables from city residents.",
      kk: "Білім беру бағдарламалары бар экологиялық орталық. Қала тұрғындарынан қайта өңдеуге болатын материалдарды жинайды.",
    },
    address: {
      ru: "пр. Туран 56, корп. 1",
      en: "Turan Ave 56, block 1",
      kk: "Тұран д-лы 56, 1-корп.",
    },
    position: { lat: 51.1190, lng: 71.4455 },
    materials: ["plastic", "paper", "glass", "metal", "bottles", "electronics"],
    schedule: { weekdays: "09:00–18:00", saturday: "10:00–15:00", sunday: null },
    phone: "+7 (7172) 58-00-21",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    slug: "taza-qala-taza-el",
    category: "hub",
    name: {
      ru: "Taza Qala — Taza El",
      en: "Taza Qala — Taza El",
      kk: "Таза Қала — Таза Ел",
    },
    description: {
      ru: "Государственная инициатива по раздельному сбору отходов. Принимает пластик, бумагу и стекло.",
      en: "Government waste-separation initiative. Accepts plastic, paper and glass.",
      kk: "Қалдықтарды бөлек жинаудың мемлекеттік бастамасы. Пластик, қағаз және шыны қабылдайды.",
    },
    address: {
      ru: "ул. Кабанбай батыра 11",
      en: "Kabanbay Batyr St 11",
      kk: "Қабанбай батыр к. 11",
    },
    position: { lat: 51.1089, lng: 71.4312 },
    materials: ["plastic", "paper", "glass"],
    schedule: { weekdays: "08:00–17:00", saturday: "09:00–13:00", sunday: null },
    phone: "+7 (7172) 21-30-00",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-02-10",
  },
  {
    id: "5",
    slug: "astana-qagazy",
    category: "hub",
    name: {
      ru: "AstanaQagazy",
      en: "AstanaQagazy",
      kk: "AstanaQaғazy",
    },
    description: {
      ru: "Специализируется на скупке и переработке бумаги и картона. Возможен вывоз крупных партий.",
      en: "Specialises in buying and recycling paper and cardboard. Large-batch collection available.",
      kk: "Қағаз бен картонды сатып алу және қайта өңдеуге маманданған. Ірі партияларды тасымалдау мүмкіндігі бар.",
    },
    address: {
      ru: "ул. Жибек жолы 22",
      en: "Zhibek Zholy St 22",
      kk: "Жібек жолы к. 22",
    },
    position: { lat: 51.1670, lng: 71.4121 },
    materials: ["paper"],
    schedule: { weekdays: "09:00–18:00", saturday: null, sunday: null },
    phone: "+7 (7172) 33-45-67",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-02-20",
  },
  {
    id: "6",
    slug: "eco-polygon-astana",
    category: "hub",
    name: {
      ru: "Экополигон Астаны",
      en: "Eco Polygon of Astana",
      kk: "Астана Экополигоны",
    },
    description: {
      ru: "Сертифицированный полигон для приёма промышленных и опасных отходов. Только для юридических лиц.",
      en: "Certified facility for industrial and hazardous waste. Organisations only.",
      kk: "Өнеркәсіптік және қауіпті қалдықтарды қабылдауға арналған сертификатталған полигон. Тек заңды тұлғаларға.",
    },
    address: {
      ru: "Объездная дорога, 15 км от центра",
      en: "Ring Road, 15 km from centre",
      kk: "Айналма жол, орталықтан 15 шақырым",
    },
    position: { lat: 51.0941, lng: 71.5501 },
    materials: ["industrial", "metal", "electronics", "batteries"],
    schedule: { weekdays: "08:00–17:00", saturday: null, sunday: null },
    phone: "+7 (7172) 70-00-01",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-03-01",
  },

  // ── KIOSKS (category: "kiosk") ───────────────────────────────

  {
    id: "7",
    slug: "ls-ecolife-kiosk-1",
    category: "kiosk",
    name: {
      ru: "LS Ecolife — Киоск Байтерек",
      en: "LS Ecolife — Bayterek Kiosk",
      kk: "LS Ecolife — Байтерек киоскі",
    },
    description: {
      ru: "Пункт раздельного сбора рядом с монументом Байтерек.",
      en: "Waste-separation point near the Bayterek monument.",
      kk: "Байтерек ескерткіші жанындағы бөлек жинау нүктесі.",
    },
    address: {
      ru: "пр. Нурсултана Назарбаева, у монумента Байтерек",
      en: "Nursultan Nazarbayev Ave, near Bayterek",
      kk: "Нұрсұлтан Назарбаев д-лы, Байтерек жанында",
    },
    position: { lat: 51.1280, lng: 71.4302 },
    materials: ["plastic", "paper", "glass", "aluminium"],
    schedule: { weekdays: "10:00–20:00", saturday: "10:00–20:00", sunday: "10:00–18:00" },
    phone: null,
    website: "https://lsecolife.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-05",
  },
  {
    id: "8",
    slug: "ls-ecolife-kiosk-2",
    category: "kiosk",
    name: {
      ru: "LS Ecolife — Киоск Хан Шатыр",
      en: "LS Ecolife — Khan Shatyr Kiosk",
      kk: "LS Ecolife — Хан Шатыр киоскі",
    },
    description: {
      ru: "Пункт сбора у торгового центра Хан Шатыр.",
      en: "Collection point near Khan Shatyr shopping centre.",
      kk: "Хан Шатыр сауда орталығы жанындағы жинау нүктесі.",
    },
    address: {
      ru: "пр. Туран, у ТЦ Хан Шатыр",
      en: "Turan Ave, near Khan Shatyr",
      kk: "Тұран д-лы, Хан Шатыр жанында",
    },
    position: { lat: 51.1312, lng: 71.4098 },
    materials: ["plastic", "paper", "aluminium", "bottles"],
    schedule: { weekdays: "10:00–20:00", saturday: "10:00–20:00", sunday: "11:00–18:00" },
    phone: null,
    website: "https://lsecolife.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-05",
  },
  {
    id: "9",
    slug: "ls-ecolife-kiosk-3",
    category: "kiosk",
    name: {
      ru: "LS Ecolife — Киоск ЖК Европа",
      en: "LS Ecolife — Europa Residential Kiosk",
      kk: "LS Ecolife — Еуропа ТК киоскі",
    },
    description: {
      ru: "Контейнер для раздельного сбора у жилого комплекса Европа.",
      en: "Separate-collection container at Europa residential complex.",
      kk: "Еуропа тұрғын кешені жанындағы бөлек жинауға арналған контейнер.",
    },
    address: {
      ru: "ул. Достык 13, ЖК Европа",
      en: "Dostyk St 13, Europa Complex",
      kk: "Достық к. 13, Еуропа кешені",
    },
    position: { lat: 51.1551, lng: 71.4488 },
    materials: ["plastic", "paper", "glass"],
    schedule: { weekdays: "00:00–23:59", saturday: "00:00–23:59", sunday: "00:00–23:59" },
    phone: null,
    website: "https://lsecolife.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-06",
  },
  {
    id: "10",
    slug: "ls-ecolife-kiosk-4",
    category: "kiosk",
    name: {
      ru: "LS Ecolife — Киоск Левый берег",
      en: "LS Ecolife — Left Bank Kiosk",
      kk: "LS Ecolife — Сол жақ жағалау киоскі",
    },
    description: {
      ru: "Пункт раздельного сбора в деловом районе Левого берега.",
      en: "Recycling point in the Left Bank business district.",
      kk: "Сол жақ жағалаудың іскерлік ауданындағы бөлек жинау нүктесі.",
    },
    address: {
      ru: "пр. Кабанбай батыра 53",
      en: "Kabanbay Batyr Ave 53",
      kk: "Қабанбай батыр д-лы 53",
    },
    position: { lat: 51.1061, lng: 71.4640 },
    materials: ["plastic", "paper", "aluminium"],
    schedule: { weekdays: "09:00–19:00", saturday: "10:00–17:00", sunday: null },
    phone: null,
    website: "https://lsecolife.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-06",
  },
  {
    id: "11",
    slug: "sparklo-rvm-mega-silk-way",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Мега Силк Вэй",
      en: "Sparklo RVM — Mega Silk Way",
      kk: "Sparklo — Мега Силк Уэй автоматы",
    },
    description: {
      ru: "Фандомат (автомат приёма тары) в торговом центре Мега Силк Вэй. Принимает ПЭТ-бутылки и алюминиевые банки, начисляет бонусы.",
      en: "Reverse vending machine at Mega Silk Way mall. Accepts PET bottles and aluminium cans, awards bonus points.",
      kk: "Мега Силк Уэй сауда орталығындағы фандомат. ПЭТ бөтелкелер мен алюминий банкаларды қабылдайды, бонустар есептейді.",
    },
    address: {
      ru: "ТЦ Мега Силк Вэй, 1 этаж",
      en: "Mega Silk Way Mall, 1st floor",
      kk: "Мега Силк Уэй СО, 1-қабат",
    },
    position: { lat: 51.0974, lng: 71.4102 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-10",
  },
  {
    id: "12",
    slug: "sparklo-rvm-esil-mall",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Есіл Молл",
      en: "Sparklo RVM — Esil Mall",
      kk: "Sparklo — Есіл Молл автоматы",
    },
    description: {
      ru: "Фандомат в Есіл Молл. Принимает ПЭТ-бутылки и алюминиевые банки.",
      en: "Reverse vending machine at Esil Mall. Accepts PET bottles and aluminium cans.",
      kk: "Есіл Моллдағы фандомат. ПЭТ бөтелкелер мен алюминий банкаларды қабылдайды.",
    },
    address: {
      ru: "ТЦ Есіл Молл, ул. Достык 5",
      en: "Esil Mall, Dostyk St 5",
      kk: "Есіл Молл, Достық к. 5",
    },
    position: { lat: 51.1209, lng: 71.4681 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-10",
  },
  {
    id: "13",
    slug: "sparklo-rvm-arman",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Арман",
      en: "Sparklo RVM — Arman",
      kk: "Sparklo — Арман автоматы",
    },
    description: {
      ru: "Фандомат у ТРЦ Арман. Принимает ПЭТ-бутылки и алюминиевые банки.",
      en: "Reverse vending machine near Arman mall. Accepts PET bottles and aluminium cans.",
      kk: "Арман ТСО жанындағы фандомат. ПЭТ бөтелкелер мен алюминий банкаларды қабылдайды.",
    },
    address: {
      ru: "ТРЦ Арман, пр. Республики 37",
      en: "Arman Mall, Respubliki Ave 37",
      kk: "Арман ТСО, Республика д-лы 37",
    },
    position: { lat: 51.1780, lng: 71.4333 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-10",
  },
  {
    id: "14",
    slug: "sparklo-rvm-city-mall",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат City Mall",
      en: "Sparklo RVM — City Mall",
      kk: "Sparklo — City Mall автоматы",
    },
    description: {
      ru: "Фандомат в City Mall. Принимает ПЭТ-бутылки и алюминиевые банки.",
      en: "Reverse vending machine at City Mall. Accepts PET bottles and aluminium cans.",
      kk: "City Mall-дағы фандомат. ПЭТ бөтелкелер мен алюминий банкаларды қабылдайды.",
    },
    address: {
      ru: "City Mall, ул. Бейбитшилик 18",
      en: "City Mall, Beibitshilik St 18",
      kk: "City Mall, Бейбітшілік к. 18",
    },
    position: { lat: 51.1640, lng: 71.4561 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-10",
  },
  {
    id: "15",
    slug: "sparklo-rvm-keruen",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Керуен",
      en: "Sparklo RVM — Keruen",
      kk: "Sparklo — Керуен автоматы",
    },
    description: {
      ru: "Фандомат в ТРЦ Керуен. Принимает ПЭТ-бутылки и алюминиевые банки.",
      en: "Reverse vending machine at Keruen mall. Accepts PET bottles and aluminium cans.",
      kk: "Керуен ТСО-дағы фандомат.",
    },
    address: {
      ru: "ТРЦ Керуен, ул. Сейфуллина 51",
      en: "Keruen Mall, Seifullin St 51",
      kk: "Керуен ТСО, Сейфуллин к. 51",
    },
    position: { lat: 51.1801, lng: 71.4489 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-10",
  },
  {
    id: "16",
    slug: "sparklo-rvm-forum",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Forum",
      en: "Sparklo RVM — Forum",
      kk: "Sparklo — Forum автоматы",
    },
    description: {
      ru: "Фандомат в ТЦ Forum. Принимает ПЭТ-бутылки и алюминиевые банки.",
      en: "Reverse vending machine at Forum mall. Accepts PET bottles and aluminium cans.",
      kk: "Forum сауда орталығындағы фандомат.",
    },
    address: {
      ru: "ТЦ Forum, пр. Кабанбай батыра 62",
      en: "Forum Mall, Kabanbay Batyr Ave 62",
      kk: "Forum СО, Қабанбай батыр д-лы 62",
    },
    position: { lat: 51.1050, lng: 71.4780 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-10",
  },
  {
    id: "17",
    slug: "sparklo-rvm-grand-park",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Grand Park",
      en: "Sparklo RVM — Grand Park",
      kk: "Sparklo — Grand Park автоматы",
    },
    description: {
      ru: "Фандомат у торгового центра Grand Park.",
      en: "Reverse vending machine near Grand Park shopping centre.",
      kk: "Grand Park сауда орталығы жанындағы фандомат.",
    },
    address: {
      ru: "ТЦ Grand Park, ул. Кунаева 12",
      en: "Grand Park, Kunayev St 12",
      kk: "Grand Park, Қонаев к. 12",
    },
    position: { lat: 51.0880, lng: 71.4022 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-11",
  },
  {
    id: "18",
    slug: "sparklo-rvm-zaman",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Заман",
      en: "Sparklo RVM — Zaman",
      kk: "Sparklo — Заман автоматы",
    },
    description: {
      ru: "Фандомат в ТЦ Заман.",
      en: "Reverse vending machine at Zaman shopping centre.",
      kk: "Заман сауда орталығындағы фандомат.",
    },
    address: {
      ru: "ТЦ Заман, ул. Тауелсиздик 21",
      en: "Zaman Mall, Tauelsizdeek St 21",
      kk: "Заман СО, Тәуелсіздік к. 21",
    },
    position: { lat: 51.1725, lng: 71.4210 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-11",
  },
  {
    id: "19",
    slug: "likekomek-clothes",
    category: "kiosk",
    name: {
      ru: "Likekomek — Благотворительный контейнер",
      en: "Likekomek — Charity Clothing Bin",
      kk: "Likekomek — Қайырымдылық киім контейнері",
    },
    description: {
      ru: "Благотворительный контейнер для одежды и обуви. Вещи идут нуждающимся семьям Астаны.",
      en: "Charity bin for clothing and footwear. Items go to families in need in Astana.",
      kk: "Киім мен аяқ киімге арналған қайырымдылық контейнері. Заттар Астананың мұқтаж отбасыларына береді.",
    },
    address: {
      ru: "ул. Иманова 15, у подъезда №2",
      en: "Imanov St 15, entrance 2",
      kk: "Иманов к. 15, №2 кіреберіс",
    },
    position: { lat: 51.1620, lng: 71.4390 },
    materials: ["clothes"],
    schedule: { weekdays: "00:00–23:59", saturday: "00:00–23:59", sunday: "00:00–23:59" },
    phone: null,
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-03-15",
  },
  {
    id: "20",
    slug: "algys-clothes",
    category: "kiosk",
    name: {
      ru: "ALGYS — Контейнер для одежды",
      en: "ALGYS — Clothing Donation Bin",
      kk: "ALGYS — Киім қайырымдылық контейнері",
    },
    description: {
      ru: "Благотворительная организация ALGYS. Принимает одежду, игрушки, книги.",
      en: "Charity organisation ALGYS. Accepts clothes, toys and books.",
      kk: "ALGYS қайырымдылық ұйымы. Киім, ойыншықтар және кітаптарды қабылдайды.",
    },
    address: {
      ru: "ул. Мангилик Ел 55",
      en: "Mangilik El St 55",
      kk: "Мәңгілік Ел к. 55",
    },
    position: { lat: 51.1101, lng: 71.4558 },
    materials: ["clothes"],
    schedule: { weekdays: "00:00–23:59", saturday: "00:00–23:59", sunday: "00:00–23:59" },
    phone: "+7 (701) 888-22-11",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-03-15",
  },
  {
    id: "21",
    slug: "eco-paper-buyback",
    category: "kiosk",
    name: {
      ru: "Эко-Бумага — Пункт скупки",
      en: "Eco-Paper — Buy-back Point",
      kk: "Эко-Қағаз — Сатып алу нүктесі",
    },
    description: {
      ru: "Скупают макулатуру по рыночной цене. Принимают газеты, картон, архивы.",
      en: "Buys waste paper at market price. Accepts newspapers, cardboard, archives.",
      kk: "Макулатураны нарықтық бағамен сатып алады. Газеттер, картон, мұрағаттарды қабылдайды.",
    },
    address: {
      ru: "ул. Желтоксан 38",
      en: "Zheltoksan St 38",
      kk: "Желтоқсан к. 38",
    },
    position: { lat: 51.1490, lng: 71.3985 },
    materials: ["paper"],
    schedule: { weekdays: "09:00–17:00", saturday: "09:00–14:00", sunday: null },
    phone: "+7 (7172) 44-55-66",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-03-20",
  },
  {
    id: "22",
    slug: "green-city-electronics",
    category: "hub",
    name: {
      ru: "Green City — Электроника",
      en: "Green City — Electronics",
      kk: "Green City — Электроника",
    },
    description: {
      ru: "Специализированный пункт приёма старой электроники и батареек. Утилизация по всем нормам безопасности.",
      en: "Specialised drop-off for old electronics and batteries. Disposal meets all safety standards.",
      kk: "Ескі электроника мен батареяларды қабылдайтын мамандандырылған нүкте.",
    },
    address: {
      ru: "ул. Сейфуллина 12, корп. 3",
      en: "Seifullin St 12, block 3",
      kk: "Сейфуллин к. 12, 3-корп.",
    },
    position: { lat: 51.1855, lng: 71.4455 },
    materials: ["electronics", "batteries"],
    schedule: { weekdays: "10:00–18:00", saturday: "10:00–15:00", sunday: null },
    phone: "+7 (7172) 91-22-33",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-04-01",
  },
];
