import type { Location } from "@/types";

// ────────────────────────────────────────────────────────────
//  Mock locations — all real Astana recycling points
//  sourced from v1 (green-map-astana) + expanded
// ────────────────────────────────────────────────────────────

export const mockLocations: Location[] = [
  // ── BIG HUBS (category: "hub") ──────────────────────────────

  {
    id: "1",
    slug: "kazrecycle-service",
    category: "hub",
    name: {
      ru: "KazRecycleService ТОО",
      en: "KazRecycleService LLP",
      kk: "KazRecycleService ЖШС",
    },
    description: {
      ru: "Крупный промышленный переработчик. Принимает пластик, бумагу, стекло и металл оптом от организаций и частных лиц.",
      en: "Major industrial recycler. Accepts plastic, paper, glass and metal in bulk from organisations and individuals.",
      kk: "Ірі өнеркәсіптік қайта өңдеуші. Ұйымдардан және жеке тұлғалардан жаппай пластик, қағаз, шыны және металл қабылдайды.",
    },
    address: {
      ru: "Промышленная зона, ул. Металлургов 12",
      en: "Industrial zone, Metallurgov St 12",
      kk: "Өнеркәсіп аймағы, Металлургтар к. 12",
    },
    position: { lat: 51.1522, lng: 71.4891 },
    materials: ["plastic", "paper", "glass", "metal", "industrial"],
    schedule: { weekdays: "08:00–18:00", saturday: "09:00–14:00", sunday: null },
    phone: "+7 (7172) 45-12-33",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    slug: "ls-ecolife-hub",
    category: "hub",
    name: {
      ru: "LS Ecolife — Центральный хаб",
      en: "LS Ecolife — Central Hub",
      kk: "LS Ecolife — Орталық хаб",
    },
    description: {
      ru: "Главный центр сбора вторсырья сети LS Ecolife. Принимает широкий спектр материалов, есть консультант.",
      en: "Main collection centre of the LS Ecolife network. Wide range of materials accepted, staff on site.",
      kk: "LS Ecolife желісінің негізгі жинау орталығы. Материалдардың кең ауқымы қабылданады, кеңесші бар.",
    },
    address: {
      ru: "ул. Сарыарқа 31А",
      en: "Saryarka St 31A",
      kk: "Сарыарқа к. 31А",
    },
    position: { lat: 51.1405, lng: 71.4018 },
    materials: ["plastic", "paper", "glass", "metal", "aluminium", "bottles"],
    schedule: { weekdays: "09:00–19:00", saturday: "10:00–17:00", sunday: null },
    phone: "+7 700 503-33-03",
    website: "https://ls.com.kz",
    photos: [],
    verified: true,
    createdAt: "2024-01-15",
  },
  {
    id: "3",
    slug: "astana-taza-alem",
    category: "hub",
    name: {
      ru: "Astana Taza Alem",
      en: "Astana Taza Alem",
      kk: "Astana Taza Älem",
    },
    description: {
      ru: "Экологический центр с образовательными программами. Принимает вторсырьё от жителей города.",
      en: "Ecological centre with educational programmes. Collects recyclables from city residents.",
      kk: "Білім беру бағдарламалары бар экологиялық орталық. Қала тұрғындарынан қайта өңдеуге болатын материалдарды жинайды.",
    },
    address: {
      ru: "пр. Туран 56, корп. 1",
      en: "Turan Ave 56, block 1",
      kk: "Тұран д-лы 56, 1-корп.",
    },
    position: { lat: 51.1190, lng: 71.4455 },
    materials: ["plastic", "paper", "glass", "metal", "bottles", "electronics"],
    schedule: { weekdays: "09:00–18:00", saturday: "10:00–15:00", sunday: null },
    phone: "+7 (7172) 58-00-21",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    slug: "taza-qala-taza-el",
    category: "hub",
    name: {
      ru: "Taza Qala — Taza El",
      en: "Taza Qala — Taza El",
      kk: "Таза Қала — Таза Ел",
    },
    description: {
      ru: "Государственная инициатива по раздельному сбору отходов. Принимает пластик, бумагу и стекло.",
      en: "Government waste-separation initiative. Accepts plastic, paper and glass.",
      kk: "Қалдықтарды бөлек жинаудың мемлекеттік бастамасы. Пластик, қағаз және шыны қабылдайды.",
    },
    address: {
      ru: "ул. Кабанбай батыра 11",
      en: "Kabanbay Batyr St 11",
      kk: "Қабанбай батыр к. 11",
    },
    position: { lat: 51.1089, lng: 71.4312 },
    materials: ["plastic", "paper", "glass"],
    schedule: { weekdays: "08:00–17:00", saturday: "09:00–13:00", sunday: null },
    phone: "+7 (7172) 21-30-00",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-02-10",
  },
  {
    id: "5",
    slug: "astana-qagazy",
    category: "hub",
    name: {
      ru: "AstanaQagazy",
      en: "AstanaQagazy",
      kk: "AstanaQaғazy",
    },
    description: {
      ru: "Специализируется на скупке и переработке бумаги и картона. Возможен вывоз крупных партий.",
      en: "Specialises in buying and recycling paper and cardboard. Large-batch collection available.",
      kk: "Қағаз бен картонды сатып алу және қайта өңдеуге маманданған. Ірі партияларды тасымалдау мүмкіндігі бар.",
    },
    address: {
      ru: "ул. Жибек жолы 22",
      en: "Zhibek Zholy St 22",
      kk: "Жібек жолы к. 22",
    },
    position: { lat: 51.1670, lng: 71.4121 },
    materials: ["paper"],
    schedule: { weekdays: "09:00–18:00", saturday: null, sunday: null },
    phone: "+7 (7172) 33-45-67",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-02-20",
  },
  {
    id: "6",
    slug: "eco-polygon-astana",
    category: "hub",
    name: {
      ru: "Экополигон Астаны",
      en: "Eco Polygon of Astana",
      kk: "Астана Экополигоны",
    },
    description: {
      ru: "Сертифицированный полигон для приёма промышленных и опасных отходов. Только для юридических лиц.",
      en: "Certified facility for industrial and hazardous waste. Organisations only.",
      kk: "Өнеркәсіптік және қауіпті қалдықтарды қабылдауға арналған сертификатталған полигон. Тек заңды тұлғаларға.",
    },
    address: {
      ru: "Объездная дорога, 15 км от центра",
      en: "Ring Road, 15 km from centre",
      kk: "Айналма жол, орталықтан 15 шақырым",
    },
    position: { lat: 51.0941, lng: 71.5501 },
    materials: ["industrial", "metal", "electronics", "batteries"],
    schedule: { weekdays: "08:00–17:00", saturday: null, sunday: null },
    phone: "+7 (7172) 70-00-01",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-03-01",
  },

  // ── KIOSKS (category: "kiosk") ───────────────────────────────

  {
    id: "7",
    slug: "ls-ecolife-kiosk-1",
    category: "kiosk",
    name: {
      ru: "LS Ecolife — Киоск Байтерек",
      en: "LS Ecolife — Bayterek Kiosk",
      kk: "LS Ecolife — Байтерек киоскі",
    },
    description: {
      ru: "Пункт раздельного сбора рядом с монументом Байтерек.",
      en: "Waste-separation point near the Bayterek monument.",
      kk: "Байтерек ескерткіші жанындағы бөлек жинау нүктесі.",
    },
    address: {
      ru: "пр. Нурсултана Назарбаева, у монумента Байтерек",
      en: "Nursultan Nazarbayev Ave, near Bayterek",
      kk: "Нұрсұлтан Назарбаев д-лы, Байтерек жанында",
    },
    position: { lat: 51.1280, lng: 71.4302 },
    materials: ["plastic", "paper", "glass", "aluminium"],
    schedule: { weekdays: "10:00–20:00", saturday: "10:00–20:00", sunday: "10:00–18:00" },
    phone: null,
    website: "https://ls.com.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-05",
  },
  {
    id: "8",
    slug: "ls-ecolife-kiosk-2",
    category: "kiosk",
    name: {
      ru: "LS Ecolife — Киоск Хан Шатыр",
      en: "LS Ecolife — Khan Shatyr Kiosk",
      kk: "LS Ecolife — Хан Шатыр киоскі",
    },
    description: {
      ru: "Пункт сбора у торгового центра Хан Шатыр.",
      en: "Collection point near Khan Shatyr shopping centre.",
      kk: "Хан Шатыр сауда орталығы жанындағы жинау нүктесі.",
    },
    address: {
      ru: "пр. Туран, у ТЦ Хан Шатыр",
      en: "Turan Ave, near Khan Shatyr",
      kk: "Тұран д-лы, Хан Шатыр жанында",
    },
    position: { lat: 51.1312, lng: 71.4098 },
    materials: ["plastic", "paper", "aluminium", "bottles"],
    schedule: { weekdays: "10:00–20:00", saturday: "10:00–20:00", sunday: "11:00–18:00" },
    phone: null,
    website: "https://ls.com.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-05",
  },
  {
    id: "9",
    slug: "ls-ecolife-kiosk-3",
    category: "kiosk",
    name: {
      ru: "LS Ecolife — Киоск ЖК Европа",
      en: "LS Ecolife — Europa Residential Kiosk",
      kk: "LS Ecolife — Еуропа ТК киоскі",
    },
    description: {
      ru: "Контейнер для раздельного сбора у жилого комплекса Европа.",
      en: "Separate-collection container at Europa residential complex.",
      kk: "Еуропа тұрғын кешені жанындағы бөлек жинауға арналған контейнер.",
    },
    address: {
      ru: "ул. Достык 13, ЖК Европа",
      en: "Dostyk St 13, Europa Complex",
      kk: "Достық к. 13, Еуропа кешені",
    },
    position: { lat: 51.1551, lng: 71.4488 },
    materials: ["plastic", "paper", "glass"],
    schedule: { weekdays: "00:00–23:59", saturday: "00:00–23:59", sunday: "00:00–23:59" },
    phone: null,
    website: "https://ls.com.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-06",
  },
  {
    id: "10",
    slug: "ls-ecolife-kiosk-4",
    category: "kiosk",
    name: {
      ru: "LS Ecolife — Киоск Левый берег",
      en: "LS Ecolife — Left Bank Kiosk",
      kk: "LS Ecolife — Сол жақ жағалау киоскі",
    },
    description: {
      ru: "Пункт раздельного сбора в деловом районе Левого берега.",
      en: "Recycling point in the Left Bank business district.",
      kk: "Сол жақ жағалаудың іскерлік ауданындағы бөлек жинау нүктесі.",
    },
    address: {
      ru: "пр. Кабанбай батыра 53",
      en: "Kabanbay Batyr Ave 53",
      kk: "Қабанбай батыр д-лы 53",
    },
    position: { lat: 51.1061, lng: 71.4640 },
    materials: ["plastic", "paper", "aluminium"],
    schedule: { weekdays: "09:00–19:00", saturday: "10:00–17:00", sunday: null },
    phone: null,
    website: "https://ls.com.kz",
    photos: [],
    verified: true,
    createdAt: "2024-03-06",
  },
  {
    id: "11",
    slug: "sparklo-rvm-mega-silk-way",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Мега Силк Вэй",
      en: "Sparklo RVM — Mega Silk Way",
      kk: "Sparklo — Мега Силк Уэй автоматы",
    },
    description: {
      ru: "Фандомат Sparklo. Статус работы не подтверждён — проверьте актуальность через приложение Sparklo перед посещением.",
      en: "Sparklo reverse vending machine. Operating status unconfirmed — check the Sparklo app before visiting.",
      kk: "Sparklo фандоматы. Жұмыс мәртебесі расталмаған — баруды жоспарламас бұрын Sparklo қосымшасын тексеріңіз.",
    },
    address: {
      ru: "ТЦ Мега Силк Вэй, 1 этаж",
      en: "Mega Silk Way Mall, 1st floor",
      kk: "Мега Силк Уэй СО, 1-қабат",
    },
    position: { lat: 51.0974, lng: 71.4102 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-10",
  },
  {
    id: "12",
    slug: "sparklo-rvm-esil-mall",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Есіл Молл",
      en: "Sparklo RVM — Esil Mall",
      kk: "Sparklo — Есіл Молл автоматы",
    },
    description: {
      ru: "Фандомат Sparklo. Статус работы не подтверждён — проверьте актуальность через приложение Sparklo перед посещением.",
      en: "Sparklo reverse vending machine. Operating status unconfirmed — check the Sparklo app before visiting.",
      kk: "Sparklo фандоматы. Жұмыс мәртебесі расталмаған — баруды жоспарламас бұрын Sparklo қосымшасын тексеріңіз.",
    },
    address: {
      ru: "ТЦ Есіл Молл, ул. Достык 5",
      en: "Esil Mall, Dostyk St 5",
      kk: "Есіл Молл, Достық к. 5",
    },
    position: { lat: 51.1209, lng: 71.4681 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-10",
  },
  {
    id: "13",
    slug: "sparklo-rvm-arman",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Арман",
      en: "Sparklo RVM — Arman",
      kk: "Sparklo — Арман автоматы",
    },
    description: {
      ru: "Фандомат Sparklo. Статус работы не подтверждён — проверьте актуальность через приложение Sparklo перед посещением.",
      en: "Sparklo reverse vending machine. Operating status unconfirmed — check the Sparklo app before visiting.",
      kk: "Sparklo фандоматы. Жұмыс мәртебесі расталмаған — баруды жоспарламас бұрын Sparklo қосымшасын тексеріңіз.",
    },
    address: {
      ru: "ТРЦ Арман, пр. Республики 37",
      en: "Arman Mall, Respubliki Ave 37",
      kk: "Арман ТСО, Республика д-лы 37",
    },
    position: { lat: 51.1780, lng: 71.4333 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-10",
  },
  {
    id: "14",
    slug: "sparklo-rvm-city-mall",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат City Mall",
      en: "Sparklo RVM — City Mall",
      kk: "Sparklo — City Mall автоматы",
    },
    description: {
      ru: "Фандомат Sparklo. Статус работы не подтверждён — проверьте актуальность через приложение Sparklo перед посещением.",
      en: "Sparklo reverse vending machine. Operating status unconfirmed — check the Sparklo app before visiting.",
      kk: "Sparklo фандоматы. Жұмыс мәртебесі расталмаған — баруды жоспарламас бұрын Sparklo қосымшасын тексеріңіз.",
    },
    address: {
      ru: "City Mall, ул. Бейбитшилик 18",
      en: "City Mall, Beibitshilik St 18",
      kk: "City Mall, Бейбітшілік к. 18",
    },
    position: { lat: 51.1640, lng: 71.4561 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-10",
  },
  {
    id: "15",
    slug: "sparklo-rvm-keruen",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Керуен",
      en: "Sparklo RVM — Keruen",
      kk: "Sparklo — Керуен автоматы",
    },
    description: {
      ru: "Фандомат Sparklo. Статус работы не подтверждён — проверьте актуальность через приложение Sparklo перед посещением.",
      en: "Sparklo reverse vending machine. Operating status unconfirmed — check the Sparklo app before visiting.",
      kk: "Sparklo фандоматы. Жұмыс мәртебесі расталмаған — баруды жоспарламас бұрын Sparklo қосымшасын тексеріңіз.",
    },
    address: {
      ru: "ТРЦ Керуен, ул. Сейфуллина 51",
      en: "Keruen Mall, Seifullin St 51",
      kk: "Керуен ТСО, Сейфуллин к. 51",
    },
    position: { lat: 51.1801, lng: 71.4489 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-10",
  },
  {
    id: "16",
    slug: "sparklo-rvm-forum",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Forum",
      en: "Sparklo RVM — Forum",
      kk: "Sparklo — Forum автоматы",
    },
    description: {
      ru: "Фандомат Sparklo. Статус работы не подтверждён — проверьте актуальность через приложение Sparklo перед посещением.",
      en: "Sparklo reverse vending machine. Operating status unconfirmed — check the Sparklo app before visiting.",
      kk: "Sparklo фандоматы. Жұмыс мәртебесі расталмаған — баруды жоспарламас бұрын Sparklo қосымшасын тексеріңіз.",
    },
    address: {
      ru: "ТЦ Forum, пр. Кабанбай батыра 62",
      en: "Forum Mall, Kabanbay Batyr Ave 62",
      kk: "Forum СО, Қабанбай батыр д-лы 62",
    },
    position: { lat: 51.1050, lng: 71.4780 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-10",
  },
  {
    id: "17",
    slug: "sparklo-rvm-grand-park",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Grand Park",
      en: "Sparklo RVM — Grand Park",
      kk: "Sparklo — Grand Park автоматы",
    },
    description: {
      ru: "Фандомат Sparklo. Статус работы не подтверждён — проверьте актуальность через приложение Sparklo перед посещением.",
      en: "Sparklo reverse vending machine. Operating status unconfirmed — check the Sparklo app before visiting.",
      kk: "Sparklo фандоматы. Жұмыс мәртебесі расталмаған — баруды жоспарламас бұрын Sparklo қосымшасын тексеріңіз.",
    },
    address: {
      ru: "ТЦ Grand Park, ул. Кунаева 12",
      en: "Grand Park, Kunayev St 12",
      kk: "Grand Park, Қонаев к. 12",
    },
    position: { lat: 51.0880, lng: 71.4022 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-11",
  },
  {
    id: "18",
    slug: "sparklo-rvm-zaman",
    category: "kiosk",
    name: {
      ru: "Sparklo — Автомат Заман",
      en: "Sparklo RVM — Zaman",
      kk: "Sparklo — Заман автоматы",
    },
    description: {
      ru: "Фандомат Sparklo. Статус работы не подтверждён — проверьте актуальность через приложение Sparklo перед посещением.",
      en: "Sparklo reverse vending machine. Operating status unconfirmed — check the Sparklo app before visiting.",
      kk: "Sparklo фандоматы. Жұмыс мәртебесі расталмаған — баруды жоспарламас бұрын Sparklo қосымшасын тексеріңіз.",
    },
    address: {
      ru: "ТЦ Заман, ул. Тауелсиздик 21",
      en: "Zaman Mall, Tauelsizdeek St 21",
      kk: "Заман СО, Тәуелсіздік к. 21",
    },
    position: { lat: 51.1725, lng: 71.4210 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–21:00", saturday: "10:00–21:00", sunday: "11:00–20:00" },
    phone: null,
    website: "https://sparklo.kz",
    photos: [],
    verified: false,
    createdAt: "2024-03-11",
  },
  {
    id: "19",
    slug: "likekomek-clothes",
    category: "kiosk",
    name: {
      ru: "Likekomek — Благотворительный контейнер",
      en: "Likekomek — Charity Clothing Bin",
      kk: "Likekomek — Қайырымдылық киім контейнері",
    },
    description: {
      ru: "Благотворительный контейнер для одежды и обуви. Вещи идут нуждающимся семьям Астаны.",
      en: "Charity bin for clothing and footwear. Items go to families in need in Astana.",
      kk: "Киім мен аяқ киімге арналған қайырымдылық контейнері. Заттар Астананың мұқтаж отбасыларына береді.",
    },
    address: {
      ru: "ул. Иманова 15, у подъезда №2",
      en: "Imanov St 15, entrance 2",
      kk: "Иманов к. 15, №2 кіреберіс",
    },
    position: { lat: 51.1620, lng: 71.4390 },
    materials: ["clothes"],
    schedule: { weekdays: "00:00–23:59", saturday: "00:00–23:59", sunday: "00:00–23:59" },
    phone: null,
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-03-15",
  },
  {
    id: "20",
    slug: "algys-clothes",
    category: "kiosk",
    name: {
      ru: "ALGYS — Контейнер для одежды",
      en: "ALGYS — Clothing Donation Bin",
      kk: "ALGYS — Киім қайырымдылық контейнері",
    },
    description: {
      ru: "Благотворительная организация ALGYS. Принимает одежду, игрушки, книги.",
      en: "Charity organisation ALGYS. Accepts clothes, toys and books.",
      kk: "ALGYS қайырымдылық ұйымы. Киім, ойыншықтар және кітаптарды қабылдайды.",
    },
    address: {
      ru: "ул. Мангилик Ел 55",
      en: "Mangilik El St 55",
      kk: "Мәңгілік Ел к. 55",
    },
    position: { lat: 51.1101, lng: 71.4558 },
    materials: ["clothes"],
    schedule: { weekdays: "00:00–23:59", saturday: "00:00–23:59", sunday: "00:00–23:59" },
    phone: "+7 (701) 888-22-11",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-03-15",
  },
  {
    id: "21",
    slug: "eco-paper-buyback",
    category: "kiosk",
    name: {
      ru: "Эко-Бумага — Пункт скупки",
      en: "Eco-Paper — Buy-back Point",
      kk: "Эко-Қағаз — Сатып алу нүктесі",
    },
    description: {
      ru: "Скупают макулатуру по рыночной цене. Принимают газеты, картон, архивы.",
      en: "Buys waste paper at market price. Accepts newspapers, cardboard, archives.",
      kk: "Макулатураны нарықтық бағамен сатып алады. Газеттер, картон, мұрағаттарды қабылдайды.",
    },
    address: {
      ru: "ул. Желтоксан 38",
      en: "Zheltoksan St 38",
      kk: "Желтоқсан к. 38",
    },
    position: { lat: 51.1490, lng: 71.3985 },
    materials: ["paper"],
    schedule: { weekdays: "09:00–17:00", saturday: "09:00–14:00", sunday: null },
    phone: "+7 (7172) 44-55-66",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-03-20",
  },
  {
    id: "22",
    slug: "green-city-electronics",
    category: "hub",
    name: {
      ru: "Green City — Электроника",
      en: "Green City — Electronics",
      kk: "Green City — Электроника",
    },
    description: {
      ru: "Специализированный пункт приёма старой электроники и батареек. Утилизация по всем нормам безопасности.",
      en: "Specialised drop-off for old electronics and batteries. Disposal meets all safety standards.",
      kk: "Ескі электроника мен батареяларды қабылдайтын мамандандырылған нүкте.",
    },
    address: {
      ru: "ул. Сейфуллина 12, корп. 3",
      en: "Seifullin St 12, block 3",
      kk: "Сейфуллин к. 12, 3-корп.",
    },
    position: { lat: 51.1855, lng: 71.4455 },
    materials: ["electronics", "batteries"],
    schedule: { weekdays: "10:00–18:00", saturday: "10:00–15:00", sunday: null },
    phone: "+7 (7172) 91-22-33",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-04-01",
  },

  // ── LS Ecolife additional branches ─────────────────────────

  {
    id: "23",
    slug: "ls-ecolife-shonanauly",
    category: "hub",
    name: {
      ru: "LS Ecolife — Телжан Шонанулы",
      en: "LS Ecolife — Telzhan Shonanuly",
      kk: "LS Ecolife — Телжан Шонанулы",
    },
    description: {
      ru: "Пункт приёма вторсырья сети LS Ecolife. Принимает картон, макулатуру, плёнку, ПЭТ-бутылки, алюминий, стекло и одежду.",
      en: "LS Ecolife network recycling point. Accepts cardboard, waste paper, film, PET bottles, aluminium, glass and clothing.",
      kk: "LS Ecolife желісінің қайта өңдеу нүктесі. Картон, макулатура, пленка, ПЭТ бөтелкелер, алюминий, шыны және киімді қабылдайды.",
    },
    address: {
      ru: "ул. Телжан Шонанулы, 36А",
      en: "Telzhan Shonanuly St 36A",
      kk: "Телжан Шонанулы к. 36А",
    },
    position: { lat: 51.1295, lng: 71.4012 },
    materials: ["paper", "plastic", "glass", "aluminium", "bottles", "clothes"],
    schedule: { weekdays: "09:00–20:00", saturday: "09:00–18:00", sunday: "09:00–18:00" },
    phone: "+7 700 503-33-03",
    website: "https://ls.com.kz",
    photos: [],
    verified: true,
    createdAt: "2024-04-10",
  },
  {
    id: "24",
    slug: "ls-ecolife-mustafina",
    category: "hub",
    name: {
      ru: "LS Ecolife — Габидена Мустафина",
      en: "LS Ecolife — Gabiden Mustafin",
      kk: "LS Ecolife — Ғабиден Мұстафин",
    },
    description: {
      ru: "Пункт приёма вторсырья LS Ecolife. Принимает пластик, бумагу, стекло, алюминий и текстиль.",
      en: "LS Ecolife recycling drop-off. Accepts plastic, paper, glass, aluminium and textiles.",
      kk: "LS Ecolife қабылдау нүктесі. Пластик, қағаз, шыны, алюминий және тоқыма қабылдайды.",
    },
    address: {
      ru: "ул. Габидена Мустафина, 17/1",
      en: "Gabiden Mustafin St 17/1",
      kk: "Ғабиден Мұстафин к. 17/1",
    },
    position: { lat: 51.1582, lng: 71.4455 },
    materials: ["paper", "plastic", "glass", "aluminium", "bottles", "clothes"],
    schedule: { weekdays: "09:00–18:00", saturday: "09:00–18:00", sunday: null },
    phone: "+7 700 503-33-03",
    website: "https://ls.com.kz",
    photos: [],
    verified: true,
    createdAt: "2024-04-10",
  },
  {
    id: "25",
    slug: "ls-ecolife-koshkarbayeva",
    category: "hub",
    name: {
      ru: "LS Ecolife — Кошкарбаева",
      en: "LS Ecolife — Koshkarbayeva",
      kk: "LS Ecolife — Қошқарбаева",
    },
    description: {
      ru: "Пункт приёма вторсырья LS Ecolife на проспекте Кошкарбаева.",
      en: "LS Ecolife recycling drop-off on Koshkarbayeva Ave.",
      kk: "Қошқарбаева даңғылындағы LS Ecolife қайта өңдеу нүктесі.",
    },
    address: {
      ru: "просп. Рахимжана Кошкарбаева, 44",
      en: "Rakhimzhan Koshkarbayev Ave 44",
      kk: "Рахымжан Қошқарбаев д-лы 44",
    },
    position: { lat: 51.1748, lng: 71.3905 },
    materials: ["paper", "plastic", "glass", "aluminium", "bottles", "clothes"],
    schedule: { weekdays: "10:00–19:00", saturday: "10:00–19:00", sunday: "10:00–14:00" },
    phone: "+7 700 503-33-03",
    website: "https://ls.com.kz",
    photos: [],
    verified: true,
    createdAt: "2024-04-10",
  },

  // ── AstanaCleanTime / Зелёная станция ──────────────────────

  {
    id: "26",
    slug: "astanacleantime-dostyk",
    category: "hub",
    name: {
      ru: "AstanaCleanTime — Достык",
      en: "AstanaCleanTime — Dostyk",
      kk: "AstanaCleanTime — Достық",
    },
    description: {
      ru: "Сеть экопунктов AstanaCleanTime (Зелёная Станция). Оплата за вторсырьё: 5–100 тг/кг. Принимает бумагу, картон, плёнку, ПЭТ-бутылки, стекло и алюминий.",
      en: "AstanaCleanTime eco-station chain (Green Station). Pays 5–100 tenge/kg. Accepts paper, cardboard, film, PET bottles, glass and aluminium.",
      kk: "AstanaCleanTime экостанциялар желісі (Жасыл Станция). 5–100 тг/кг төлейді. Қағаз, картон, пленка, ПЭТ бөтелкелер, шыны және алюминийді қабылдайды.",
    },
    address: {
      ru: "ул. Достык, 5/1",
      en: "Dostyk St 5/1",
      kk: "Достық к. 5/1",
    },
    position: { lat: 51.1209, lng: 71.4671 },
    materials: ["paper", "plastic", "glass", "aluminium", "bottles"],
    schedule: { weekdays: "09:30–19:00", saturday: "09:30–19:00", sunday: null },
    phone: "+7 701 351-37-00",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-04-15",
  },
  {
    id: "27",
    slug: "astanacleantime-turkestan",
    category: "hub",
    name: {
      ru: "AstanaCleanTime — Түркістан",
      en: "AstanaCleanTime — Turkestan",
      kk: "AstanaCleanTime — Түркістан",
    },
    description: {
      ru: "Экопункт AstanaCleanTime. Принимает бумагу, картон, полиэтилен, ПЭТ-бутылки, стекло и алюминий.",
      en: "AstanaCleanTime eco-point. Accepts paper, cardboard, polyethylene, PET bottles, glass and aluminium.",
      kk: "AstanaCleanTime эконүктесі. Қағаз, картон, полиэтилен, ПЭТ бөтелкелер, шыны және алюминий қабылдайды.",
    },
    address: {
      ru: "ул. Түркістан, 30",
      en: "Turkestan St 30",
      kk: "Түркістан к. 30",
    },
    position: { lat: 51.1052, lng: 71.4502 },
    materials: ["paper", "plastic", "glass", "aluminium", "bottles"],
    schedule: { weekdays: "09:30–19:00", saturday: "09:30–19:00", sunday: null },
    phone: "+7 701 351-37-00",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-04-15",
  },
  {
    id: "28",
    slug: "astanacleantime-imanova",
    category: "hub",
    name: {
      ru: "AstanaCleanTime — Иманова",
      en: "AstanaCleanTime — Imanova",
      kk: "AstanaCleanTime — Иманова",
    },
    description: {
      ru: "Экопункт AstanaCleanTime на улице Иманова. Принимает вторсырьё с оплатой за килограмм.",
      en: "AstanaCleanTime eco-point on Imanova St. Accepts recyclables with payment per kilogram.",
      kk: "Иманова к-сіндегі AstanaCleanTime эконүктесі. Вторсырьені килограммы үшін ақы төлеп қабылдайды.",
    },
    address: {
      ru: "ул. Иманова, 50/1",
      en: "Imanova St 50/1",
      kk: "Иманова к. 50/1",
    },
    position: { lat: 51.1620, lng: 71.4368 },
    materials: ["paper", "plastic", "glass", "aluminium", "bottles"],
    schedule: { weekdays: "09:30–19:00", saturday: "09:30–19:00", sunday: null },
    phone: "+7 701 351-37-00",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-04-15",
  },

  // ── Taza Qala (updated / new locations) ────────────────────

  {
    id: "29",
    slug: "taza-qala-mangilik-el",
    category: "hub",
    name: {
      ru: "Taza Qala — Мәңгілік Ел",
      en: "Taza Qala — Mangilik El",
      kk: "Taza Qala — Мәңгілік Ел",
    },
    description: {
      ru: "Полноцикличный переработчик ПЭТ-тары и другого вторсырья. Принимает ПЭТ-бутылки, алюминиевые банки, стекло, бумагу, ПЭВП-канистры.",
      en: "Full-cycle PET and secondary materials recycler. Accepts PET bottles, aluminium cans, glass, paper, HDPE canisters.",
      kk: "ПЭТ ыдыс және өзге де қайта өңделетін шикізаттың толық циклді өңдеушісі.",
    },
    address: {
      ru: "просп. Мәңгілік Ел, 50",
      en: "Mangilik El Ave 50",
      kk: "Мәңгілік Ел д-лы 50",
    },
    position: { lat: 51.0935, lng: 71.4380 },
    materials: ["plastic", "paper", "glass", "aluminium", "bottles"],
    schedule: { weekdays: "09:00–18:00", saturday: "09:00–14:00", sunday: null },
    phone: "+7 705 875-82-32",
    website: "https://taza-qala.kz",
    photos: [],
    verified: true,
    createdAt: "2024-04-20",
  },

  // ── Azia Group — hazardous waste ───────────────────────────

  {
    id: "30",
    slug: "azia-group-hazardous",
    category: "hub",
    name: {
      ru: "Azia Group — Опасные отходы",
      en: "Azia Group — Hazardous Waste",
      kk: "Azia Group — Қауіпті қалдықтар",
    },
    description: {
      ru: "Лицензированный переработчик опасных отходов. Принимает ртутьсодержащие приборы, люминесцентные лампы, принтеры, картриджи, аккумуляторы, автошины, антифриз и оргтехнику.",
      en: "Licensed hazardous waste processor. Accepts mercury-containing devices, fluorescent lamps, printers, cartridges, accumulators, tyres, antifreeze and office equipment.",
      kk: "Лицензияланған қауіпті қалдықтарды өңдеуші. Сынап бар аспаптарды, люминесцентті шамдарды, принтерлерді, картридждерді, аккумуляторларды, автокөлік дөңгелектерін, антифризді және оргтехниканы қабылдайды.",
    },
    address: {
      ru: "ул. Манаса, 23/2, 3 этаж",
      en: "Manas St 23/2, 3rd floor",
      kk: "Манас к. 23/2, 3-қабат",
    },
    position: { lat: 51.1685, lng: 71.4295 },
    materials: ["electronics", "batteries", "industrial"],
    schedule: { weekdays: "09:00–18:00", saturday: null, sunday: null },
    phone: "+7 708 425-44-16",
    website: "https://aziagroup.kz",
    photos: [],
    verified: true,
    createdAt: "2024-04-22",
  },

  // ── KazVtorChermet — metals ─────────────────────────────────

  {
    id: "31",
    slug: "kazytorchermet-abaya",
    category: "hub",
    name: {
      ru: "Казвторчермет — Абая",
      en: "KazVtorChermet — Abay Ave",
      kk: "Қазвторшермет — Абай д-лы",
    },
    description: {
      ru: "Астанинский филиал АО Казвторчермет. Скупает чёрный и цветной металлолом, принимает вторичное сырьё от предприятий и частных лиц.",
      en: "Astana branch of KazVtorChermet JSC. Buys ferrous and non-ferrous scrap metal, accepts secondary materials from businesses and individuals.",
      kk: "ҚазВторЧермет АҚ Астана филиалы. Қара және түсті металл сынықтарын сатып алады.",
    },
    address: {
      ru: "просп. Абая, 97, офис 203",
      en: "Abay Ave 97, office 203",
      kk: "Абай д-лы 97, 203-кеңсе",
    },
    position: { lat: 51.1825, lng: 71.4488 },
    materials: ["metal", "industrial"],
    schedule: { weekdays: "09:00–19:00", saturday: "09:00–19:00", sunday: null },
    phone: "+7 708 618-08-88",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-04-25",
  },

  // ── KazMetKor — metals & batteries ─────────────────────────

  {
    id: "32",
    slug: "kazmetkor-ushkonyar",
    category: "hub",
    name: {
      ru: "КазМетКор — Приём вторсырья",
      en: "KazMetKor — Secondary Materials",
      kk: "КазМетКор — Қайталама шикізат",
    },
    description: {
      ru: "Ежедневный приём вторичного сырья: металл, аккумуляторы, электроника. Работает без выходных.",
      en: "Daily collection of secondary materials: metal, accumulators, electronics. Open every day.",
      kk: "Металл, аккумулятор, электроника — күн сайын қайталама шикізат қабылдайды.",
    },
    address: {
      ru: "ул. Ушконыр, 1/2",
      en: "Ushkonyir St 1/2",
      kk: "Ұшқоныр к. 1/2",
    },
    position: { lat: 51.1158, lng: 71.4825 },
    materials: ["metal", "batteries", "electronics"],
    schedule: { weekdays: "09:00–19:00", saturday: "09:00–19:00", sunday: "09:00–19:00" },
    phone: "+7 771 700-23-86",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-04-28",
  },

  // ── Eco-RBK ─────────────────────────────────────────────────

  {
    id: "33",
    slug: "eco-rbk-beibitshilik",
    category: "hub",
    name: {
      ru: "Eco-RBK",
      en: "Eco-RBK",
      kk: "Eco-RBK",
    },
    description: {
      ru: "Пункт приёма и переработки вторсырья в районе Бейбитшилик.",
      en: "Recycling collection and processing point in the Beibitshilik area.",
      kk: "Бейбітшілік ауданындағы қайта өңдеу жинау нүктесі.",
    },
    address: {
      ru: "ул. Бейбитшилик, 43",
      en: "Beibitshilik St 43",
      kk: "Бейбітшілік к. 43",
    },
    position: { lat: 51.1642, lng: 71.4540 },
    materials: ["plastic", "paper", "metal"],
    schedule: { weekdays: "08:30–17:30", saturday: null, sunday: null },
    phone: "+7 747 790-93-60",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-05-01",
  },

  // ── Оператор РОП / Жасыл Даму ──────────────────────────────

  {
    id: "34",
    slug: "rop-operator-mangilik-el",
    category: "hub",
    name: {
      ru: "Оператор РОП — Жасыл Даму",
      en: "ROP Operator — Jasyl Damu",
      kk: "РОП операторы — Жасыл Даму",
    },
    description: {
      ru: "Государственный оператор расширенной ответственности производителя (РОП). Координирует раздельный сбор и переработку упаковки в Казахстане.",
      en: "State extended producer responsibility (ROP) operator. Coordinates separate collection and recycling of packaging across Kazakhstan.",
      kk: "Өндірушінің кеңейтілген жауапкершілігінің (РОП) мемлекеттік операторы.",
    },
    address: {
      ru: "просп. Мәңгілік Ел, 18, 1 этаж (БЦ «Финансовый центр»)",
      en: "Mangilik El Ave 18, 1st floor (Finance Centre)",
      kk: "Мәңгілік Ел д-лы 18, 1-қабат (Қаржы орталығы)",
    },
    position: { lat: 51.0905, lng: 71.4310 },
    materials: ["plastic", "paper", "glass", "metal"],
    schedule: { weekdays: "09:00–18:00", saturday: null, sunday: null },
    phone: "+7 7172 72-79-60",
    website: "https://recycle.kz",
    photos: [],
    verified: true,
    createdAt: "2024-05-05",
  },

  // ── Ecoplatform fandomat — MEGA Silk Way ───────────────────

  {
    id: "35",
    slug: "ecoplatform-mega-silk-way",
    category: "kiosk",
    name: {
      ru: "Экоплатформа — Фандомат MEGA Silk Way",
      en: "Ecoplatform RVM — MEGA Silk Way",
      kk: "Экоплатформа — MEGA Silk Way фандоматы",
    },
    description: {
      ru: "Фандомат Ecoplatform: принимает алюминиевые банки, ПЭТ-бутылки и пластиковые крышки. Приложение не нужно. Работает ежедневно.",
      en: "Ecoplatform reverse vending machine: accepts aluminium cans, PET bottles and plastic caps. No app needed. Open daily.",
      kk: "Ecoplatform фандоматы: алюминий банкалар, ПЭТ бөтелкелер және пластик қақпақтарды қабылдайды.",
    },
    address: {
      ru: "ТРЦ MEGA Silk Way, просп. Кабанбай батыра 62, 1 этаж",
      en: "MEGA Silk Way, Kabanbay Batyr Ave 62, 1st floor",
      kk: "MEGA Silk Way, Қабанбай батыр д-лы 62, 1-қабат",
    },
    position: { lat: 51.0902, lng: 71.4205 },
    materials: ["bottles", "aluminium"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-05-08",
  },

  // ── Sulpak in-store battery/electronics drop-offs ──────────

  {
    id: "36",
    slug: "sulpak-astana-mall",
    category: "kiosk",
    name: {
      ru: "Sulpak — Батарейки/Электроника (Astana Mall)",
      en: "Sulpak — Battery & Electronics Drop-off (Astana Mall)",
      kk: "Sulpak — Батарейка/Электроника (Astana Mall)",
    },
    description: {
      ru: "Контейнер для батареек и мелкой электроники у кассы Sulpak в Astana Mall. Бесплатная утилизация.",
      en: "Battery and small electronics drop-off container at Sulpak checkout in Astana Mall. Free recycling.",
      kk: "Astana Mall-дағы Sulpak кассасы жанындағы батарейка және ұсақ электрониканы тастауға арналған контейнер.",
    },
    address: {
      ru: "ТРЦ Astana Mall, просп. Тауелсиздик 34",
      en: "Astana Mall, Tauelsizdeek Ave 34",
      kk: "Astana Mall, Тәуелсіздік д-лы 34",
    },
    position: { lat: 51.1712, lng: 71.4195 },
    materials: ["batteries", "electronics"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: "https://www.sulpak.kz",
    photos: [],
    verified: true,
    createdAt: "2024-05-10",
  },
  {
    id: "37",
    slug: "sulpak-khan-shatyr",
    category: "kiosk",
    name: {
      ru: "Sulpak — Батарейки/Электроника (Хан Шатыр)",
      en: "Sulpak — Battery & Electronics Drop-off (Khan Shatyr)",
      kk: "Sulpak — Батарейка/Электроника (Хан Шатыр)",
    },
    description: {
      ru: "Контейнер для батареек и мелкой электроники у Sulpak в торговом центре Хан Шатыр. Бесплатная утилизация.",
      en: "Battery and small electronics drop-off at Sulpak in Khan Shatyr mall. Free recycling.",
      kk: "Хан Шатыр сауда орталығындағы Sulpak жанындағы батарейка және ұсақ электрониканы тастауға арналған контейнер.",
    },
    address: {
      ru: "ТЦ Хан Шатыр, просп. Туран 37",
      en: "Khan Shatyr, Turan Ave 37",
      kk: "Хан Шатыр, Тұран д-лы 37",
    },
    position: { lat: 51.1308, lng: 71.4089 },
    materials: ["batteries", "electronics"],
    schedule: { weekdays: "10:00–22:00", saturday: "10:00–22:00", sunday: "10:00–22:00" },
    phone: null,
    website: "https://www.sulpak.kz",
    photos: [],
    verified: true,
    createdAt: "2024-05-10",
  },

  // ── Taza Alem Astana ────────────────────────────────────────

  {
    id: "38",
    slug: "taza-alem-seifullin",
    category: "hub",
    name: {
      ru: "Taza Alem Astana",
      en: "Taza Alem Astana",
      kk: "Taza Alem Astana",
    },
    description: {
      ru: "Пункт приёма и управления вторичными материалами. Принимает различные категории вторсырья от населения и организаций.",
      en: "Secondary materials collection and management point. Accepts various recyclable categories from residents and organisations.",
      kk: "Қайталама материалдарды жинау және басқару нүктесі.",
    },
    address: {
      ru: "ул. Сейфуллина, 27/3, офис 43",
      en: "Seifullin St 27/3, office 43",
      kk: "Сейфуллин к. 27/3, 43-кеңсе",
    },
    position: { lat: 51.1810, lng: 71.4451 },
    materials: ["plastic", "paper", "glass", "metal"],
    schedule: { weekdays: "09:00–17:00", saturday: null, sunday: null },
    phone: "+7 7172 49-26-04",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-05-12",
  },

  // ── Green Station / Абылай хана ─────────────────────────────

  {
    id: "39",
    slug: "green-station-abylay-khana",
    category: "kiosk",
    name: {
      ru: "Зелёная Станция — Абылай хана",
      en: "Green Station — Abylay Khan Ave",
      kk: "Жасыл Станция — Абылай хан",
    },
    description: {
      ru: "Самостоятельный пункт раздельного сбора «Зелёная станция». Принимает бумагу, пластик, стекло и целлофан, платит за принятое сырьё.",
      en: "Independent Green Station separate-collection point. Accepts paper, plastic, glass and cellophane, pays per kilogram.",
      kk: "Дербес «Жасыл Станция» бөлек жинау нүктесі. Қағаз, пластик, шыны және целлофанды қабылдайды, килограмм үшін ақы төлейді.",
    },
    address: {
      ru: "просп. Абылай хана, 29/2",
      en: "Abylay Khan Ave 29/2",
      kk: "Абылай хан д-лы 29/2",
    },
    position: { lat: 51.1732, lng: 71.4378 },
    materials: ["paper", "plastic", "glass"],
    schedule: { weekdays: "09:00–18:00", saturday: "09:00–13:00", sunday: null },
    phone: "+7 702 502-33-62",
    website: null,
    photos: [],
    verified: true,
    createdAt: "2024-05-14",
  },
];
