import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const locations = [
  {
    slug: 'kazrecycle-service',
    category: 'hub' as const,
    nameRu: 'KazRecycleService ТОО',
    nameEn: 'KazRecycleService LLP',
    nameKk: 'KazRecycleService ЖШС',
    descriptionRu: 'Крупный промышленный переработчик. Принимает пластик, бумагу, стекло и металл оптом от организаций и частных лиц.',
    descriptionEn: 'Major industrial recycler. Accepts plastic, paper, glass and metal in bulk from organisations and individuals.',
    descriptionKk: 'Ірі өнеркәсіптік қайта өңдеуші. Ұйымдардан және жеке тұлғалардан жаппай пластик, қағаз, шыны және металл қабылдайды.',
    addressRu: 'Промышленная зона, ул. Металлургов 12',
    addressEn: 'Industrial zone, Metallurgov St 12',
    addressKk: 'Өнеркәсіп аймағы, Металлургтар к. 12',
    lat: 51.1522, lng: 71.4891,
    materials: ['plastic', 'paper', 'glass', 'metal', 'industrial'],
    scheduleWeekdays: '08:00–18:00', scheduleSaturday: '09:00–14:00', scheduleSunday: null,
    phone: '+7 (7172) 45-12-33', website: null, verified: true,
  },
  {
    slug: 'ls-ecolife-hub',
    category: 'hub' as const,
    nameRu: 'LS Ecolife — Центральный хаб',
    nameEn: 'LS Ecolife — Central Hub',
    nameKk: 'LS Ecolife — Орталық хаб',
    descriptionRu: 'Главный центр сбора вторсырья сети LS Ecolife. Принимает широкий спектр материалов, есть консультант.',
    descriptionEn: 'Main collection centre of the LS Ecolife network. Wide range of materials accepted, staff on site.',
    descriptionKk: 'LS Ecolife желісінің негізгі жинау орталығы. Материалдардың кең ауқымы қабылданады, кеңесші бар.',
    addressRu: 'ул. Сарыарқа 31А',
    addressEn: 'Saryarka St 31A',
    addressKk: 'Сарыарқа к. 31А',
    lat: 51.1405, lng: 71.4018,
    materials: ['plastic', 'paper', 'glass', 'metal', 'aluminium', 'bottles'],
    scheduleWeekdays: '09:00–19:00', scheduleSaturday: '10:00–17:00', scheduleSunday: null,
    phone: '+7 (7172) 30-77-88', website: 'https://lsecolife.kz', verified: true,
  },
  {
    slug: 'astana-taza-alem',
    category: 'hub' as const,
    nameRu: 'Astana Taza Alem',
    nameEn: 'Astana Taza Alem',
    nameKk: 'Astana Taza Älem',
    descriptionRu: 'Экологический центр с образовательными программами. Принимает вторсырьё от жителей города.',
    descriptionEn: 'Ecological centre with educational programmes. Collects recyclables from city residents.',
    descriptionKk: 'Білім беру бағдарламалары бар экологиялық орталық. Қала тұрғындарынан қайта өңдеуге болатын материалдарды жинайды.',
    addressRu: 'пр. Туран 56, корп. 1',
    addressEn: 'Turan Ave 56, block 1',
    addressKk: 'Тұран д-лы 56, 1-корп.',
    lat: 51.1190, lng: 71.4455,
    materials: ['plastic', 'paper', 'glass', 'metal', 'bottles', 'electronics'],
    scheduleWeekdays: '09:00–18:00', scheduleSaturday: '10:00–15:00', scheduleSunday: null,
    phone: '+7 (7172) 58-00-21', website: null, verified: true,
  },
  {
    slug: 'taza-qala-taza-el',
    category: 'hub' as const,
    nameRu: 'Taza Qala — Taza El',
    nameEn: 'Taza Qala — Taza El',
    nameKk: 'Таза Қала — Таза Ел',
    descriptionRu: 'Государственная инициатива по раздельному сбору отходов. Принимает пластик, бумагу и стекло.',
    descriptionEn: 'Government waste-separation initiative. Accepts plastic, paper and glass.',
    descriptionKk: 'Қалдықтарды бөлек жинаудың мемлекеттік бастамасы. Пластик, қағаз және шыны қабылдайды.',
    addressRu: 'ул. Кабанбай батыра 11',
    addressEn: 'Kabanbay Batyr St 11',
    addressKk: 'Қабанбай батыр к. 11',
    lat: 51.1089, lng: 71.4312,
    materials: ['plastic', 'paper', 'glass'],
    scheduleWeekdays: '08:00–17:00', scheduleSaturday: '09:00–13:00', scheduleSunday: null,
    phone: '+7 (7172) 21-30-00', website: null, verified: true,
  },
  {
    slug: 'astana-qagazy',
    category: 'hub' as const,
    nameRu: 'AstanaQagazy',
    nameEn: 'AstanaQagazy',
    nameKk: 'AstanaQaғazy',
    descriptionRu: 'Специализируется на скупке и переработке бумаги и картона. Возможен вывоз крупных партий.',
    descriptionEn: 'Specialises in buying and recycling paper and cardboard. Large-batch collection available.',
    descriptionKk: 'Қағаз бен картонды сатып алу және қайта өңдеуге маманданған. Ірі партияларды тасымалдау мүмкіндігі бар.',
    addressRu: 'ул. Жибек жолы 22',
    addressEn: 'Zhibek Zholy St 22',
    addressKk: 'Жібек жолы к. 22',
    lat: 51.1670, lng: 71.4121,
    materials: ['paper'],
    scheduleWeekdays: '09:00–18:00', scheduleSaturday: null, scheduleSunday: null,
    phone: '+7 (7172) 33-45-67', website: null, verified: true,
  },
  {
    slug: 'eco-polygon-astana',
    category: 'hub' as const,
    nameRu: 'Экополигон Астаны',
    nameEn: 'Eco Polygon of Astana',
    nameKk: 'Астана Экополигоны',
    descriptionRu: 'Сертифицированный полигон для приёма промышленных и опасных отходов. Только для юридических лиц.',
    descriptionEn: 'Certified facility for industrial and hazardous waste. Organisations only.',
    descriptionKk: 'Өнеркәсіптік және қауіпті қалдықтарды қабылдауға арналған сертификатталған полигон. Тек заңды тұлғаларға.',
    addressRu: 'Объездная дорога, 15 км от центра',
    addressEn: 'Ring Road, 15 km from centre',
    addressKk: 'Айналма жол, орталықтан 15 шақырым',
    lat: 51.0941, lng: 71.5501,
    materials: ['industrial', 'metal', 'electronics', 'batteries'],
    scheduleWeekdays: '08:00–17:00', scheduleSaturday: null, scheduleSunday: null,
    phone: '+7 (7172) 70-00-01', website: null, verified: true,
  },
  {
    slug: 'ls-ecolife-kiosk-1',
    category: 'kiosk' as const,
    nameRu: 'LS Ecolife — Киоск Байтерек',
    nameEn: 'LS Ecolife — Bayterek Kiosk',
    nameKk: 'LS Ecolife — Байтерек киоскі',
    descriptionRu: 'Пункт раздельного сбора рядом с монументом Байтерек.',
    descriptionEn: 'Waste-separation point near the Bayterek monument.',
    descriptionKk: 'Байтерек ескерткіші жанындағы бөлек жинау нүктесі.',
    addressRu: 'пр. Нурсултана Назарбаева, у монумента Байтерек',
    addressEn: 'Nursultan Nazarbayev Ave, near Bayterek',
    addressKk: 'Нұрсұлтан Назарбаев д-лы, Байтерек жанында',
    lat: 51.1280, lng: 71.4302,
    materials: ['plastic', 'paper', 'glass', 'aluminium'],
    scheduleWeekdays: '10:00–20:00', scheduleSaturday: '10:00–20:00', scheduleSunday: '10:00–18:00',
    phone: null, website: 'https://lsecolife.kz', verified: true,
  },
  {
    slug: 'ls-ecolife-kiosk-2',
    category: 'kiosk' as const,
    nameRu: 'LS Ecolife — Киоск Хан Шатыр',
    nameEn: 'LS Ecolife — Khan Shatyr Kiosk',
    nameKk: 'LS Ecolife — Хан Шатыр киоскі',
    descriptionRu: 'Пункт сбора у торгового центра Хан Шатыр.',
    descriptionEn: 'Collection point near Khan Shatyr shopping centre.',
    descriptionKk: 'Хан Шатыр сауда орталығы жанындағы жинау нүктесі.',
    addressRu: 'пр. Туран, у ТЦ Хан Шатыр',
    addressEn: 'Turan Ave, near Khan Shatyr',
    addressKk: 'Тұран д-лы, Хан Шатыр жанында',
    lat: 51.1312, lng: 71.4098,
    materials: ['plastic', 'paper', 'aluminium', 'bottles'],
    scheduleWeekdays: '10:00–20:00', scheduleSaturday: '10:00–20:00', scheduleSunday: '11:00–18:00',
    phone: null, website: 'https://lsecolife.kz', verified: true,
  },
  {
    slug: 'ls-ecolife-kiosk-3',
    category: 'kiosk' as const,
    nameRu: 'LS Ecolife — Киоск ЖК Европа',
    nameEn: 'LS Ecolife — Europa Residential Kiosk',
    nameKk: 'LS Ecolife — Еуропа ТК киоскі',
    descriptionRu: 'Контейнер для раздельного сбора у жилого комплекса Европа.',
    descriptionEn: 'Separate-collection container at Europa residential complex.',
    descriptionKk: 'Еуропа тұрғын кешені жанындағы бөлек жинауға арналған контейнер.',
    addressRu: 'ул. Достык 13, ЖК Европа',
    addressEn: 'Dostyk St 13, Europa Complex',
    addressKk: 'Достық к. 13, Еуропа кешені',
    lat: 51.1551, lng: 71.4488,
    materials: ['plastic', 'paper', 'glass'],
    scheduleWeekdays: '00:00–23:59', scheduleSaturday: '00:00–23:59', scheduleSunday: '00:00–23:59',
    phone: null, website: 'https://lsecolife.kz', verified: true,
  },
  {
    slug: 'ls-ecolife-kiosk-4',
    category: 'kiosk' as const,
    nameRu: 'LS Ecolife — Киоск Левый берег',
    nameEn: 'LS Ecolife — Left Bank Kiosk',
    nameKk: 'LS Ecolife — Сол жақ жағалау киоскі',
    descriptionRu: 'Пункт раздельного сбора в деловом районе Левого берега.',
    descriptionEn: 'Recycling point in the Left Bank business district.',
    descriptionKk: 'Сол жақ жағалаудың іскерлік ауданындағы бөлек жинау нүктесі.',
    addressRu: 'пр. Кабанбай батыра 53',
    addressEn: 'Kabanbay Batyr Ave 53',
    addressKk: 'Қабанбай батыр д-лы 53',
    lat: 51.1061, lng: 71.4640,
    materials: ['plastic', 'paper', 'aluminium'],
    scheduleWeekdays: '09:00–19:00', scheduleSaturday: '10:00–17:00', scheduleSunday: null,
    phone: null, website: 'https://lsecolife.kz', verified: true,
  },
  {
    slug: 'sparklo-rvm-mega-silk-way',
    category: 'kiosk' as const,
    nameRu: 'Sparklo — Автомат Мега Силк Вэй',
    nameEn: 'Sparklo RVM — Mega Silk Way',
    nameKk: 'Sparklo — Мега Силк Уэй автоматы',
    descriptionRu: 'Фандомат в торговом центре Мега Силк Вэй. Принимает ПЭТ-бутылки и алюминиевые банки, начисляет бонусы.',
    descriptionEn: 'Reverse vending machine at Mega Silk Way mall. Accepts PET bottles and aluminium cans, awards bonus points.',
    descriptionKk: 'Мега Силк Уэй сауда орталығындағы фандомат. ПЭТ бөтелкелер мен алюминий банкаларды қабылдайды, бонустар есептейді.',
    addressRu: 'ТЦ Мега Силк Вэй, 1 этаж',
    addressEn: 'Mega Silk Way Mall, 1st floor',
    addressKk: 'Мега Силк Уэй СО, 1-қабат',
    lat: 51.0974, lng: 71.4102,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–22:00', scheduleSaturday: '10:00–22:00', scheduleSunday: '10:00–22:00',
    phone: null, website: 'https://sparklo.kz', verified: true,
  },
  {
    slug: 'sparklo-rvm-esil-mall',
    category: 'kiosk' as const,
    nameRu: 'Sparklo — Автомат Есіл Молл',
    nameEn: 'Sparklo RVM — Esil Mall',
    nameKk: 'Sparklo — Есіл Молл автоматы',
    descriptionRu: 'Фандомат в Есіл Молл. Принимает ПЭТ-бутылки и алюминиевые банки.',
    descriptionEn: 'Reverse vending machine at Esil Mall. Accepts PET bottles and aluminium cans.',
    descriptionKk: 'Есіл Моллдағы фандомат. ПЭТ бөтелкелер мен алюминий банкаларды қабылдайды.',
    addressRu: 'ТЦ Есіл Молл, ул. Достык 5',
    addressEn: 'Esil Mall, Dostyk St 5',
    addressKk: 'Есіл Молл, Достық к. 5',
    lat: 51.1209, lng: 71.4681,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–21:00', scheduleSaturday: '10:00–21:00', scheduleSunday: '11:00–20:00',
    phone: null, website: 'https://sparklo.kz', verified: true,
  },
  {
    slug: 'sparklo-rvm-arman',
    category: 'kiosk' as const,
    nameRu: 'Sparklo — Автомат Арман',
    nameEn: 'Sparklo RVM — Arman',
    nameKk: 'Sparklo — Арман автоматы',
    descriptionRu: 'Фандомат у ТРЦ Арман. Принимает ПЭТ-бутылки и алюминиевые банки.',
    descriptionEn: 'Reverse vending machine near Arman mall. Accepts PET bottles and aluminium cans.',
    descriptionKk: 'Арман ТСО жанындағы фандомат. ПЭТ бөтелкелер мен алюминий банкаларды қабылдайды.',
    addressRu: 'ТРЦ Арман, пр. Республики 37',
    addressEn: 'Arman Mall, Respubliki Ave 37',
    addressKk: 'Арман ТСО, Республика д-лы 37',
    lat: 51.1780, lng: 71.4333,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–21:00', scheduleSaturday: '10:00–21:00', scheduleSunday: '11:00–20:00',
    phone: null, website: 'https://sparklo.kz', verified: true,
  },
  {
    slug: 'sparklo-rvm-city-mall',
    category: 'kiosk' as const,
    nameRu: 'Sparklo — Автомат City Mall',
    nameEn: 'Sparklo RVM — City Mall',
    nameKk: 'Sparklo — City Mall автоматы',
    descriptionRu: 'Фандомат в City Mall. Принимает ПЭТ-бутылки и алюминиевые банки.',
    descriptionEn: 'Reverse vending machine at City Mall. Accepts PET bottles and aluminium cans.',
    descriptionKk: 'City Mall-дағы фандомат. ПЭТ бөтелкелер мен алюминий банкаларды қабылдайды.',
    addressRu: 'City Mall, ул. Бейбитшилик 18',
    addressEn: 'City Mall, Beibitshilik St 18',
    addressKk: 'City Mall, Бейбітшілік к. 18',
    lat: 51.1640, lng: 71.4561,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–21:00', scheduleSaturday: '10:00–21:00', scheduleSunday: '11:00–20:00',
    phone: null, website: 'https://sparklo.kz', verified: true,
  },
  {
    slug: 'sparklo-rvm-keruen',
    category: 'kiosk' as const,
    nameRu: 'Sparklo — Автомат Керуен',
    nameEn: 'Sparklo RVM — Keruen',
    nameKk: 'Sparklo — Керуен автоматы',
    descriptionRu: 'Фандомат в ТРЦ Керуен. Принимает ПЭТ-бутылки и алюминиевые банки.',
    descriptionEn: 'Reverse vending machine at Keruen mall. Accepts PET bottles and aluminium cans.',
    descriptionKk: 'Керуен ТСО-дағы фандомат.',
    addressRu: 'ТРЦ Керуен, ул. Сейфуллина 51',
    addressEn: 'Keruen Mall, Seifullin St 51',
    addressKk: 'Керуен ТСО, Сейфуллин к. 51',
    lat: 51.1801, lng: 71.4489,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–22:00', scheduleSaturday: '10:00–22:00', scheduleSunday: '10:00–22:00',
    phone: null, website: 'https://sparklo.kz', verified: true,
  },
  {
    slug: 'sparklo-rvm-forum',
    category: 'kiosk' as const,
    nameRu: 'Sparklo — Автомат Forum',
    nameEn: 'Sparklo RVM — Forum',
    nameKk: 'Sparklo — Forum автоматы',
    descriptionRu: 'Фандомат в ТЦ Forum. Принимает ПЭТ-бутылки и алюминиевые банки.',
    descriptionEn: 'Reverse vending machine at Forum mall. Accepts PET bottles and aluminium cans.',
    descriptionKk: 'Forum сауда орталығындағы фандомат.',
    addressRu: 'ТЦ Forum, пр. Кабанбай батыра 62',
    addressEn: 'Forum Mall, Kabanbay Batyr Ave 62',
    addressKk: 'Forum СО, Қабанбай батыр д-лы 62',
    lat: 51.1050, lng: 71.4780,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–22:00', scheduleSaturday: '10:00–22:00', scheduleSunday: '10:00–22:00',
    phone: null, website: 'https://sparklo.kz', verified: true,
  },
  {
    slug: 'sparklo-rvm-grand-park',
    category: 'kiosk' as const,
    nameRu: 'Sparklo — Автомат Grand Park',
    nameEn: 'Sparklo RVM — Grand Park',
    nameKk: 'Sparklo — Grand Park автоматы',
    descriptionRu: 'Фандомат у торгового центра Grand Park.',
    descriptionEn: 'Reverse vending machine near Grand Park shopping centre.',
    descriptionKk: 'Grand Park сауда орталығы жанындағы фандомат.',
    addressRu: 'ТЦ Grand Park, ул. Кунаева 12',
    addressEn: 'Grand Park, Kunayev St 12',
    addressKk: 'Grand Park, Қонаев к. 12',
    lat: 51.0880, lng: 71.4022,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–21:00', scheduleSaturday: '10:00–21:00', scheduleSunday: '11:00–20:00',
    phone: null, website: 'https://sparklo.kz', verified: true,
  },
  {
    slug: 'sparklo-rvm-zaman',
    category: 'kiosk' as const,
    nameRu: 'Sparklo — Автомат Заман',
    nameEn: 'Sparklo RVM — Zaman',
    nameKk: 'Sparklo — Заман автоматы',
    descriptionRu: 'Фандомат в ТЦ Заман.',
    descriptionEn: 'Reverse vending machine at Zaman shopping centre.',
    descriptionKk: 'Заман сауда орталығындағы фандомат.',
    addressRu: 'ТЦ Заман, ул. Тауелсиздик 21',
    addressEn: 'Zaman Mall, Tauelsizdeek St 21',
    addressKk: 'Заман СО, Тәуелсіздік к. 21',
    lat: 51.1725, lng: 71.4210,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–21:00', scheduleSaturday: '10:00–21:00', scheduleSunday: '11:00–20:00',
    phone: null, website: 'https://sparklo.kz', verified: false,
  },
  {
    slug: 'likekomek-clothes',
    category: 'kiosk' as const,
    nameRu: 'Likekomek — Благотворительный контейнер',
    nameEn: 'Likekomek — Charity Clothing Bin',
    nameKk: 'Likekomek — Қайырымдылық киім контейнері',
    descriptionRu: 'Благотворительный контейнер для одежды и обуви. Вещи идут нуждающимся семьям Астаны.',
    descriptionEn: 'Charity bin for clothing and footwear. Items go to families in need in Astana.',
    descriptionKk: 'Киім мен аяқ киімге арналған қайырымдылық контейнері. Заттар Астананың мұқтаж отбасыларына береді.',
    addressRu: 'ул. Иманова 15, у подъезда №2',
    addressEn: 'Imanov St 15, entrance 2',
    addressKk: 'Иманов к. 15, №2 кіреберіс',
    lat: 51.1620, lng: 71.4390,
    materials: ['clothes'],
    scheduleWeekdays: '00:00–23:59', scheduleSaturday: '00:00–23:59', scheduleSunday: '00:00–23:59',
    phone: null, website: null, verified: true,
  },
  {
    slug: 'algys-clothes',
    category: 'kiosk' as const,
    nameRu: 'ALGYS — Контейнер для одежды',
    nameEn: 'ALGYS — Clothing Donation Bin',
    nameKk: 'ALGYS — Киім қайырымдылық контейнері',
    descriptionRu: 'Благотворительная организация ALGYS. Принимает одежду, игрушки, книги.',
    descriptionEn: 'Charity organisation ALGYS. Accepts clothes, toys and books.',
    descriptionKk: 'ALGYS қайырымдылық ұйымы. Киім, ойыншықтар және кітаптарды қабылдайды.',
    addressRu: 'ул. Мангилик Ел 55',
    addressEn: 'Mangilik El St 55',
    addressKk: 'Мәңгілік Ел к. 55',
    lat: 51.1101, lng: 71.4558,
    materials: ['clothes'],
    scheduleWeekdays: '00:00–23:59', scheduleSaturday: '00:00–23:59', scheduleSunday: '00:00–23:59',
    phone: '+7 (701) 888-22-11', website: null, verified: true,
  },
  {
    slug: 'eco-paper-buyback',
    category: 'kiosk' as const,
    nameRu: 'Эко-Бумага — Пункт скупки',
    nameEn: 'Eco-Paper — Buy-back Point',
    nameKk: 'Эко-Қағаз — Сатып алу нүктесі',
    descriptionRu: 'Скупают макулатуру по рыночной цене. Принимают газеты, картон, архивы.',
    descriptionEn: 'Buys waste paper at market price. Accepts newspapers, cardboard, archives.',
    descriptionKk: 'Макулатураны нарықтық бағамен сатып алады. Газеттер, картон, мұрағаттарды қабылдайды.',
    addressRu: 'ул. Желтоксан 38',
    addressEn: 'Zheltoksan St 38',
    addressKk: 'Желтоқсан к. 38',
    lat: 51.1490, lng: 71.3985,
    materials: ['paper'],
    scheduleWeekdays: '09:00–17:00', scheduleSaturday: '09:00–14:00', scheduleSunday: null,
    phone: '+7 (7172) 44-55-66', website: null, verified: true,
  },
  {
    slug: 'green-city-electronics',
    category: 'hub' as const,
    nameRu: 'Green City — Электроника',
    nameEn: 'Green City — Electronics',
    nameKk: 'Green City — Электроника',
    descriptionRu: 'Специализированный пункт приёма старой электроники и батареек. Утилизация по всем нормам безопасности.',
    descriptionEn: 'Specialised drop-off for old electronics and batteries. Disposal meets all safety standards.',
    descriptionKk: 'Ескі электроника мен батареяларды қабылдайтын мамандандырылған нүкте.',
    addressRu: 'ул. Сейфуллина 12, корп. 3',
    addressEn: 'Seifullin St 12, block 3',
    addressKk: 'Сейфуллин к. 12, 3-корп.',
    lat: 51.1855, lng: 71.4455,
    materials: ['electronics', 'batteries'],
    scheduleWeekdays: '10:00–18:00', scheduleSaturday: '10:00–15:00', scheduleSunday: null,
    phone: '+7 (7172) 91-22-33', website: null, verified: true,
  },

  // ── LS Ecolife additional branches ──────────────────────────
  {
    slug: 'ls-ecolife-shonanauly',
    category: 'hub' as const,
    nameRu: 'LS Ecolife — Телжан Шонанулы',
    nameEn: 'LS Ecolife — Telzhan Shonanuly',
    nameKk: 'LS Ecolife — Телжан Шонанулы',
    descriptionRu: 'Пункт приёма вторсырья сети LS Ecolife. Принимает картон, макулатуру, плёнку, ПЭТ-бутылки, алюминий, стекло и одежду.',
    descriptionEn: 'LS Ecolife network recycling point. Accepts cardboard, waste paper, film, PET bottles, aluminium, glass and clothing.',
    descriptionKk: 'LS Ecolife желісінің қайта өңдеу нүктесі. Картон, макулатура, пленка, ПЭТ бөтелкелер, алюминий, шыны және киімді қабылдайды.',
    addressRu: 'ул. Телжан Шонанулы, 36А',
    addressEn: 'Telzhan Shonanuly St 36A',
    addressKk: 'Телжан Шонанулы к. 36А',
    lat: 51.1295, lng: 71.4012,
    materials: ['paper', 'plastic', 'glass', 'aluminium', 'bottles', 'clothes'],
    scheduleWeekdays: '09:00–20:00', scheduleSaturday: '09:00–18:00', scheduleSunday: '09:00–18:00',
    phone: '+7 700 503-33-03', website: 'https://ls.com.kz', verified: true,
  },
  {
    slug: 'ls-ecolife-mustafina',
    category: 'hub' as const,
    nameRu: 'LS Ecolife — Габидена Мустафина',
    nameEn: 'LS Ecolife — Gabiden Mustafin',
    nameKk: 'LS Ecolife — Ғабиден Мұстафин',
    descriptionRu: 'Пункт приёма вторсырья LS Ecolife. Принимает пластик, бумагу, стекло, алюминий и текстиль.',
    descriptionEn: 'LS Ecolife recycling drop-off. Accepts plastic, paper, glass, aluminium and textiles.',
    descriptionKk: 'LS Ecolife қабылдау нүктесі. Пластик, қағаз, шыны, алюминий және тоқыма қабылдайды.',
    addressRu: 'ул. Габидена Мустафина, 17/1',
    addressEn: 'Gabiden Mustafin St 17/1',
    addressKk: 'Ғабиден Мұстафин к. 17/1',
    lat: 51.1582, lng: 71.4455,
    materials: ['paper', 'plastic', 'glass', 'aluminium', 'bottles', 'clothes'],
    scheduleWeekdays: '09:00–18:00', scheduleSaturday: '09:00–18:00', scheduleSunday: null,
    phone: '+7 700 503-33-03', website: 'https://ls.com.kz', verified: true,
  },
  {
    slug: 'ls-ecolife-koshkarbayeva',
    category: 'hub' as const,
    nameRu: 'LS Ecolife — Кошкарбаева',
    nameEn: 'LS Ecolife — Koshkarbayeva',
    nameKk: 'LS Ecolife — Қошқарбаева',
    descriptionRu: 'Пункт приёма вторсырья LS Ecolife на проспекте Кошкарбаева.',
    descriptionEn: 'LS Ecolife recycling drop-off on Koshkarbayeva Ave.',
    descriptionKk: 'Қошқарбаева даңғылындағы LS Ecolife қайта өңдеу нүктесі.',
    addressRu: 'просп. Рахимжана Кошкарбаева, 44',
    addressEn: 'Rakhimzhan Koshkarbayev Ave 44',
    addressKk: 'Рахымжан Қошқарбаев д-лы 44',
    lat: 51.1748, lng: 71.3905,
    materials: ['paper', 'plastic', 'glass', 'aluminium', 'bottles', 'clothes'],
    scheduleWeekdays: '10:00–19:00', scheduleSaturday: '10:00–19:00', scheduleSunday: '10:00–14:00',
    phone: '+7 700 503-33-03', website: 'https://ls.com.kz', verified: true,
  },

  // ── AstanaCleanTime / Зелёная станция ───────────────────────
  {
    slug: 'astanacleantime-dostyk',
    category: 'hub' as const,
    nameRu: 'AstanaCleanTime — Достык',
    nameEn: 'AstanaCleanTime — Dostyk',
    nameKk: 'AstanaCleanTime — Достық',
    descriptionRu: 'Сеть экопунктов AstanaCleanTime (Зелёная Станция). Оплата за вторсырьё: 5–100 тг/кг. Принимает бумагу, картон, плёнку, ПЭТ-бутылки, стекло и алюминий.',
    descriptionEn: 'AstanaCleanTime eco-station chain (Green Station). Pays 5–100 tenge/kg. Accepts paper, cardboard, film, PET bottles, glass and aluminium.',
    descriptionKk: 'AstanaCleanTime экостанциялар желісі. 5–100 тг/кг төлейді. Қағаз, картон, пленка, ПЭТ бөтелкелер, шыны және алюминийді қабылдайды.',
    addressRu: 'ул. Достык, 5/1',
    addressEn: 'Dostyk St 5/1',
    addressKk: 'Достық к. 5/1',
    lat: 51.1209, lng: 71.4671,
    materials: ['paper', 'plastic', 'glass', 'aluminium', 'bottles'],
    scheduleWeekdays: '09:30–19:00', scheduleSaturday: '09:30–19:00', scheduleSunday: null,
    phone: '+7 701 351-37-00', website: null, verified: true,
  },
  {
    slug: 'astanacleantime-turkestan',
    category: 'hub' as const,
    nameRu: 'AstanaCleanTime — Түркістан',
    nameEn: 'AstanaCleanTime — Turkestan',
    nameKk: 'AstanaCleanTime — Түркістан',
    descriptionRu: 'Экопункт AstanaCleanTime. Принимает бумагу, картон, полиэтилен, ПЭТ-бутылки, стекло и алюминий.',
    descriptionEn: 'AstanaCleanTime eco-point. Accepts paper, cardboard, polyethylene, PET bottles, glass and aluminium.',
    descriptionKk: 'AstanaCleanTime эконүктесі. Қағаз, картон, полиэтилен, ПЭТ бөтелкелер, шыны және алюминий қабылдайды.',
    addressRu: 'ул. Түркістан, 30',
    addressEn: 'Turkestan St 30',
    addressKk: 'Түркістан к. 30',
    lat: 51.1052, lng: 71.4502,
    materials: ['paper', 'plastic', 'glass', 'aluminium', 'bottles'],
    scheduleWeekdays: '09:30–19:00', scheduleSaturday: '09:30–19:00', scheduleSunday: null,
    phone: '+7 701 351-37-00', website: null, verified: true,
  },
  {
    slug: 'astanacleantime-imanova',
    category: 'hub' as const,
    nameRu: 'AstanaCleanTime — Иманова',
    nameEn: 'AstanaCleanTime — Imanova',
    nameKk: 'AstanaCleanTime — Иманова',
    descriptionRu: 'Экопункт AstanaCleanTime на улице Иманова. Принимает вторсырьё с оплатой за килограмм.',
    descriptionEn: 'AstanaCleanTime eco-point on Imanova St. Accepts recyclables with payment per kilogram.',
    descriptionKk: 'Иманова к-сіндегі AstanaCleanTime эконүктесі.',
    addressRu: 'ул. Иманова, 50/1',
    addressEn: 'Imanova St 50/1',
    addressKk: 'Иманова к. 50/1',
    lat: 51.1620, lng: 71.4368,
    materials: ['paper', 'plastic', 'glass', 'aluminium', 'bottles'],
    scheduleWeekdays: '09:30–19:00', scheduleSaturday: '09:30–19:00', scheduleSunday: null,
    phone: '+7 701 351-37-00', website: null, verified: true,
  },

  // ── Taza Qala ────────────────────────────────────────────────
  {
    slug: 'taza-qala-mangilik-el',
    category: 'hub' as const,
    nameRu: 'Taza Qala — Мәңгілік Ел',
    nameEn: 'Taza Qala — Mangilik El',
    nameKk: 'Taza Qala — Мәңгілік Ел',
    descriptionRu: 'Полноцикличный переработчик ПЭТ-тары и другого вторсырья. Принимает ПЭТ-бутылки, алюминиевые банки, стекло, бумагу, ПЭВП-канистры.',
    descriptionEn: 'Full-cycle PET and secondary materials recycler. Accepts PET bottles, aluminium cans, glass, paper, HDPE canisters.',
    descriptionKk: 'ПЭТ ыдыс және өзге де қайта өңделетін шикізаттың толық циклді өңдеушісі.',
    addressRu: 'просп. Мәңгілік Ел, 50',
    addressEn: 'Mangilik El Ave 50',
    addressKk: 'Мәңгілік Ел д-лы 50',
    lat: 51.0935, lng: 71.4380,
    materials: ['plastic', 'paper', 'glass', 'aluminium', 'bottles'],
    scheduleWeekdays: '09:00–18:00', scheduleSaturday: '09:00–14:00', scheduleSunday: null,
    phone: '+7 705 875-82-32', website: 'https://taza-qala.kz', verified: true,
  },

  // ── Azia Group ───────────────────────────────────────────────
  {
    slug: 'azia-group-hazardous',
    category: 'hub' as const,
    nameRu: 'Azia Group — Опасные отходы',
    nameEn: 'Azia Group — Hazardous Waste',
    nameKk: 'Azia Group — Қауіпті қалдықтар',
    descriptionRu: 'Лицензированный переработчик опасных отходов. Принимает ртутьсодержащие приборы, люминесцентные лампы, принтеры, картриджи, аккумуляторы, автошины, антифриз и оргтехнику.',
    descriptionEn: 'Licensed hazardous waste processor. Accepts mercury-containing devices, fluorescent lamps, printers, cartridges, accumulators, tyres, antifreeze and office equipment.',
    descriptionKk: 'Лицензияланған қауіпті қалдықтарды өңдеуші. Сынап бар аспаптарды, люминесцентті шамдарды, принтерлерді, картридждерді қабылдайды.',
    addressRu: 'ул. Манаса, 23/2, 3 этаж',
    addressEn: 'Manas St 23/2, 3rd floor',
    addressKk: 'Манас к. 23/2, 3-қабат',
    lat: 51.1685, lng: 71.4295,
    materials: ['electronics', 'batteries', 'industrial'],
    scheduleWeekdays: '09:00–18:00', scheduleSaturday: null, scheduleSunday: null,
    phone: '+7 708 425-44-16', website: 'https://aziagroup.kz', verified: true,
  },

  // ── KazVtorChermet ───────────────────────────────────────────
  {
    slug: 'kazytorchermet-abaya',
    category: 'hub' as const,
    nameRu: 'Казвторчермет — Абая',
    nameEn: 'KazVtorChermet — Abay Ave',
    nameKk: 'Қазвторшермет — Абай д-лы',
    descriptionRu: 'Астанинский филиал АО Казвторчермет. Скупает чёрный и цветной металлолом, принимает вторичное сырьё от предприятий и частных лиц.',
    descriptionEn: 'Astana branch of KazVtorChermet JSC. Buys ferrous and non-ferrous scrap metal, accepts secondary materials from businesses and individuals.',
    descriptionKk: 'ҚазВторЧермет АҚ Астана филиалы. Қара және түсті металл сынықтарын сатып алады.',
    addressRu: 'просп. Абая, 97, офис 203',
    addressEn: 'Abay Ave 97, office 203',
    addressKk: 'Абай д-лы 97, 203-кеңсе',
    lat: 51.1825, lng: 71.4488,
    materials: ['metal', 'industrial'],
    scheduleWeekdays: '09:00–19:00', scheduleSaturday: '09:00–19:00', scheduleSunday: null,
    phone: '+7 708 618-08-88', website: null, verified: true,
  },

  // ── KazMetKor ────────────────────────────────────────────────
  {
    slug: 'kazmetkor-ushkonyar',
    category: 'hub' as const,
    nameRu: 'КазМетКор — Приём вторсырья',
    nameEn: 'KazMetKor — Secondary Materials',
    nameKk: 'КазМетКор — Қайталама шикізат',
    descriptionRu: 'Ежедневный приём вторичного сырья: металл, аккумуляторы, электроника. Работает без выходных.',
    descriptionEn: 'Daily collection of secondary materials: metal, accumulators, electronics. Open every day.',
    descriptionKk: 'Металл, аккумулятор, электроника — күн сайын қайталама шикізат қабылдайды.',
    addressRu: 'ул. Ушконыр, 1/2',
    addressEn: 'Ushkonyir St 1/2',
    addressKk: 'Ұшқоныр к. 1/2',
    lat: 51.1158, lng: 71.4825,
    materials: ['metal', 'batteries', 'electronics'],
    scheduleWeekdays: '09:00–19:00', scheduleSaturday: '09:00–19:00', scheduleSunday: '09:00–19:00',
    phone: '+7 771 700-23-86', website: null, verified: true,
  },

  // ── Eco-RBK ──────────────────────────────────────────────────
  {
    slug: 'eco-rbk-beibitshilik',
    category: 'hub' as const,
    nameRu: 'Eco-RBK',
    nameEn: 'Eco-RBK',
    nameKk: 'Eco-RBK',
    descriptionRu: 'Пункт приёма и переработки вторсырья в районе Бейбитшилик.',
    descriptionEn: 'Recycling collection and processing point in the Beibitshilik area.',
    descriptionKk: 'Бейбітшілік ауданындағы қайта өңдеу жинау нүктесі.',
    addressRu: 'ул. Бейбитшилик, 43',
    addressEn: 'Beibitshilik St 43',
    addressKk: 'Бейбітшілік к. 43',
    lat: 51.1642, lng: 71.4540,
    materials: ['plastic', 'paper', 'metal'],
    scheduleWeekdays: '08:30–17:30', scheduleSaturday: null, scheduleSunday: null,
    phone: '+7 747 790-93-60', website: null, verified: true,
  },

  // ── ROP Operator / Жасыл Даму ────────────────────────────────
  {
    slug: 'rop-operator-mangilik-el',
    category: 'hub' as const,
    nameRu: 'Оператор РОП — Жасыл Даму',
    nameEn: 'ROP Operator — Jasyl Damu',
    nameKk: 'РОП операторы — Жасыл Даму',
    descriptionRu: 'Государственный оператор расширенной ответственности производителя (РОП). Координирует раздельный сбор и переработку упаковки в Казахстане.',
    descriptionEn: 'State extended producer responsibility (ROP) operator. Coordinates separate collection and recycling of packaging across Kazakhstan.',
    descriptionKk: 'Өндірушінің кеңейтілген жауапкершілігінің мемлекеттік операторы.',
    addressRu: 'просп. Мәңгілік Ел, 18, 1 этаж (БЦ «Финансовый центр»)',
    addressEn: 'Mangilik El Ave 18, 1st floor (Finance Centre)',
    addressKk: 'Мәңгілік Ел д-лы 18, 1-қабат',
    lat: 51.0905, lng: 71.4310,
    materials: ['plastic', 'paper', 'glass', 'metal'],
    scheduleWeekdays: '09:00–18:00', scheduleSaturday: null, scheduleSunday: null,
    phone: '+7 7172 72-79-60', website: 'https://recycle.kz', verified: true,
  },

  // ── Ecoplatform RVM ──────────────────────────────────────────
  {
    slug: 'ecoplatform-mega-silk-way',
    category: 'kiosk' as const,
    nameRu: 'Экоплатформа — Фандомат MEGA Silk Way',
    nameEn: 'Ecoplatform RVM — MEGA Silk Way',
    nameKk: 'Экоплатформа — MEGA Silk Way фандоматы',
    descriptionRu: 'Фандомат Ecoplatform: принимает алюминиевые банки, ПЭТ-бутылки и пластиковые крышки. Приложение не нужно. Работает ежедневно.',
    descriptionEn: 'Ecoplatform reverse vending machine: accepts aluminium cans, PET bottles and plastic caps. No app needed. Open daily.',
    descriptionKk: 'Ecoplatform фандоматы: алюминий банкалар, ПЭТ бөтелкелер және пластик қақпақтарды қабылдайды.',
    addressRu: 'ТРЦ MEGA Silk Way, просп. Кабанбай батыра 62, 1 этаж',
    addressEn: 'MEGA Silk Way, Kabanbay Batyr Ave 62, 1st floor',
    addressKk: 'MEGA Silk Way, Қабанбай батыр д-лы 62, 1-қабат',
    lat: 51.0902, lng: 71.4205,
    materials: ['bottles', 'aluminium'],
    scheduleWeekdays: '10:00–22:00', scheduleSaturday: '10:00–22:00', scheduleSunday: '10:00–22:00',
    phone: null, website: null, verified: true,
  },

  // ── Sulpak drop-offs ─────────────────────────────────────────
  {
    slug: 'sulpak-astana-mall',
    category: 'kiosk' as const,
    nameRu: 'Sulpak — Батарейки/Электроника (Astana Mall)',
    nameEn: 'Sulpak — Battery & Electronics Drop-off (Astana Mall)',
    nameKk: 'Sulpak — Батарейка/Электроника (Astana Mall)',
    descriptionRu: 'Контейнер для батареек и мелкой электроники у кассы Sulpak в Astana Mall. Бесплатная утилизация.',
    descriptionEn: 'Battery and small electronics drop-off container at Sulpak checkout in Astana Mall. Free recycling.',
    descriptionKk: 'Astana Mall-дағы Sulpak кассасы жанындағы батарейка және ұсақ электрониканы тастауға арналған контейнер.',
    addressRu: 'ТРЦ Astana Mall, просп. Тауелсиздик 34',
    addressEn: 'Astana Mall, Tauelsizdeek Ave 34',
    addressKk: 'Astana Mall, Тәуелсіздік д-лы 34',
    lat: 51.1712, lng: 71.4195,
    materials: ['batteries', 'electronics'],
    scheduleWeekdays: '10:00–22:00', scheduleSaturday: '10:00–22:00', scheduleSunday: '10:00–22:00',
    phone: null, website: 'https://www.sulpak.kz', verified: true,
  },
  {
    slug: 'sulpak-khan-shatyr',
    category: 'kiosk' as const,
    nameRu: 'Sulpak — Батарейки/Электроника (Хан Шатыр)',
    nameEn: 'Sulpak — Battery & Electronics Drop-off (Khan Shatyr)',
    nameKk: 'Sulpak — Батарейка/Электроника (Хан Шатыр)',
    descriptionRu: 'Контейнер для батареек и мелкой электроники у Sulpak в торговом центре Хан Шатыр. Бесплатная утилизация.',
    descriptionEn: 'Battery and small electronics drop-off at Sulpak in Khan Shatyr mall. Free recycling.',
    descriptionKk: 'Хан Шатыр сауда орталығындағы Sulpak жанындағы батарейка және ұсақ электрониканы тастауға арналған контейнер.',
    addressRu: 'ТЦ Хан Шатыр, просп. Туран 37',
    addressEn: 'Khan Shatyr, Turan Ave 37',
    addressKk: 'Хан Шатыр, Тұран д-лы 37',
    lat: 51.1308, lng: 71.4089,
    materials: ['batteries', 'electronics'],
    scheduleWeekdays: '10:00–22:00', scheduleSaturday: '10:00–22:00', scheduleSunday: '10:00–22:00',
    phone: null, website: 'https://www.sulpak.kz', verified: true,
  },

  // ── Taza Alem Astana ─────────────────────────────────────────
  {
    slug: 'taza-alem-seifullin',
    category: 'hub' as const,
    nameRu: 'Taza Alem Astana',
    nameEn: 'Taza Alem Astana',
    nameKk: 'Taza Alem Astana',
    descriptionRu: 'Пункт приёма и управления вторичными материалами. Принимает различные категории вторсырья от населения и организаций.',
    descriptionEn: 'Secondary materials collection and management point. Accepts various recyclable categories from residents and organisations.',
    descriptionKk: 'Қайталама материалдарды жинау және басқару нүктесі.',
    addressRu: 'ул. Сейфуллина, 27/3, офис 43',
    addressEn: 'Seifullin St 27/3, office 43',
    addressKk: 'Сейфуллин к. 27/3, 43-кеңсе',
    lat: 51.1810, lng: 71.4451,
    materials: ['plastic', 'paper', 'glass', 'metal'],
    scheduleWeekdays: '09:00–17:00', scheduleSaturday: null, scheduleSunday: null,
    phone: '+7 7172 49-26-04', website: null, verified: true,
  },

  // ── Green Station / Абылай хана ──────────────────────────────
  {
    slug: 'green-station-abylay-khana',
    category: 'kiosk' as const,
    nameRu: 'Зелёная Станция — Абылай хана',
    nameEn: 'Green Station — Abylay Khan Ave',
    nameKk: 'Жасыл Станция — Абылай хан',
    descriptionRu: 'Самостоятельный пункт раздельного сбора «Зелёная станция». Принимает бумагу, пластик, стекло и целлофан, платит за принятое сырьё.',
    descriptionEn: 'Independent Green Station separate-collection point. Accepts paper, plastic, glass and cellophane, pays per kilogram.',
    descriptionKk: 'Дербес «Жасыл Станция» бөлек жинау нүктесі. Қағаз, пластик, шыны және целлофанды қабылдайды, килограмм үшін ақы төлейді.',
    addressRu: 'просп. Абылай хана, 29/2',
    addressEn: 'Abylay Khan Ave 29/2',
    addressKk: 'Абылай хан д-лы 29/2',
    lat: 51.1732, lng: 71.4378,
    materials: ['paper', 'plastic', 'glass'],
    scheduleWeekdays: '09:00–18:00', scheduleSaturday: '09:00–13:00', scheduleSunday: null,
    phone: '+7 702 502-33-62', website: null, verified: true,
  },
];

async function main() {
  console.log('Seeding database...');

  await prisma.location.deleteMany();
  console.log('Cleared existing locations');

  for (const loc of locations) {
    await prisma.location.create({
      data: {
        ...loc,
        photos: [],
      },
    });
  }

  console.log(`Seeded ${locations.length} locations`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
